export interface EmojiItem {
  char: string;
  name_zh: string;
  name_en: string;
  keywords: string[];
}

export interface EmojiGroup {
  name: string;
  groupIcon: string;
  emojis: EmojiItem[];
}

export const EMOJI_DATA: EmojiGroup[] = [
  {
    name: '表情与情感',
    groupIcon: 'Smile',
    emojis: [
      { char: '😀', name_zh: '笑脸', name_en: 'grinning face', keywords: ['smile', 'happy', '高兴', '开心'] },
      { char: '😃', name_zh: '大眼笑脸', name_en: 'grinning face with big eyes', keywords: ['smile', 'happy', '高兴', '开心'] },
      { char: '😄', name_zh: '微笑', name_en: 'grinning face with smiling eyes', keywords: ['smile', 'happy', '高兴', '开心'] },
      { char: '😁', name_zh: '露齿笑脸', name_en: 'beaming face with smiling eyes', keywords: ['smile', 'happy', '高兴', '开心'] },
      { char: '😆', name_zh: '眯眼大笑', name_en: 'grinning squinting face', keywords: ['smile', 'happy', '大笑'] },
      { char: '😅', name_zh: '苦笑', name_en: 'grinning face with sweat', keywords: ['sweat', 'smile', '汗'] },
      { char: '😂', name_zh: '笑哭', name_en: 'face with tears of joy', keywords: ['laugh', 'cry', 'tears', '哈哈', '搞笑'] },
      { char: '🤣', name_zh: '笑得满地打滚', name_en: 'rolling on the floor laughing', keywords: ['rofl', 'lmao', '大笑'] },
      { char: '🥲', name_zh: '含泪微笑', name_en: 'smiling face with tear', keywords: ['sad', 'smile', '强颜欢笑'] },
      { char: '😊', name_zh: '微笑', name_en: 'smiling face', keywords: ['smile', 'warm', '温暖'] },
      { char: '😇', name_zh: '光环笑脸', name_en: 'smiling face with halo', keywords: ['angel', 'innocent', '天使'] },
      { char: '🙂', name_zh: '微微一笑', name_en: 'slightly smiling face', keywords: ['smile', '微笑'] },
      { char: '🙃', name_zh: '倒脸', name_en: 'upside-down face', keywords: ['silly', 'sarcasm', '无语'] },
      { char: '😉', name_zh: '眨眼', name_en: 'winking face', keywords: ['wink', 'flirt', '暗示'] },
      { char: '😌', name_zh: '松了口气', name_en: 'relieved face', keywords: ['phew', 'relax', '放松'] },
      { char: '😍', name_zh: '花痴', name_en: 'smiling face with heart-eyes', keywords: ['love', 'crush', '迷恋'] },
      { char: '🥰', name_zh: '充满爱的笑脸', name_en: 'smiling face with hearts', keywords: ['love', 'affection', '喜欢', '爱'] },
      { char: '😘', name_zh: '飞吻', name_en: 'face blowing a kiss', keywords: ['kiss', 'love', '亲亲'] },
      { char: '😗', name_zh: '亲吻', name_en: 'kissing face', keywords: ['kiss', '亲吻'] },
      { char: '😙', name_zh: '微笑亲吻', name_en: 'kissing face with smiling eyes', keywords: ['kiss', 'smile', '亲吻'] },
      { char: '😚', name_zh: '闭眼亲吻', name_en: 'kissing face with closed eyes', keywords: ['kiss', '亲吻'] },
      { char: '😋', name_zh: '吐舌', name_en: 'face savoring food', keywords: ['yum', 'tasty', '好吃'] },
      { char: '😛', name_zh: '略略略', name_en: 'face with tongue', keywords: ['tongue', 'silly', '调皮'] },
      { char: '😜', name_zh: '单眼吐舌', name_en: 'winking face with tongue', keywords: ['wink', 'tongue', '调皮'] },
      { char: '🤪', name_zh: '滑稽', name_en: 'zany face', keywords: ['crazy', 'goofy', '搞怪'] },
      { char: '😝', name_zh: '眯眼吐舌', name_en: 'squinting face with tongue', keywords: ['tongue', 'laugh', '调皮'] },
      { char: '🤑', name_zh: '财迷', name_en: 'money-mouth face', keywords: ['money', 'rich', '发财'] },
      { char: '🤗', name_zh: '拥抱', name_en: 'smiling face with open hands', keywords: ['hug', '抱抱'] },
      { char: '🤭', name_zh: '捂嘴笑', name_en: 'face with hand over mouth', keywords: ['oops', 'giggle', '偷笑'] },
      { char: '🤫', name_zh: '嘘', name_en: 'shushing face', keywords: ['quiet', 'shh', '安静'] },
      { char: '🤔', name_zh: '思考', name_en: 'thinking face', keywords: ['think', 'hmm', '想', '疑问'] },
      { char: '🤐', name_zh: '闭嘴', name_en: 'zipper-mouth face', keywords: ['secret', 'quiet', '保密'] },
      { char: '🤨', name_zh: '挑眉', name_en: 'face with raised eyebrow', keywords: ['skeptical', 'sus', '怀疑'] },
      { char: '😐', name_zh: '无语', name_en: 'neutral face', keywords: ['meh', '无聊', '冷漠'] },
      { char: '😑', name_zh: '面无表情', name_en: 'expressionless face', keywords: ['blank', '无语'] },
      { char: '😶', name_zh: '没有嘴巴', name_en: 'face without mouth', keywords: ['speechless', '沉默'] },
      { char: '😏', name_zh: '得意', name_en: 'smirking face', keywords: ['smug', 'flirt', '得意'] },
      { char: '😒', name_zh: '不高兴', name_en: 'unamused face', keywords: ['annoyed', '不满'] },
      { char: '🙄', name_zh: '翻白眼', name_en: 'face with rolling eyes', keywords: ['eye roll', '无奈'] },
      { char: '😬', name_zh: '龇牙', name_en: 'grimacing face', keywords: ['awkward', 'eek', '尴尬'] },
      { char: '🤥', name_zh: '说谎', name_en: 'lying face', keywords: ['liar', 'pinocchio', '骗子'] },
      { char: '😌', name_zh: '如释重负', name_en: 'relieved face', keywords: ['phew', 'relax', '放心'] },
      { char: '😔', name_zh: '沉思', name_en: 'pensive face', keywords: ['sad', 'depressed', '沮丧'] },
      { char: '😪', name_zh: '困', name_en: 'sleepy face', keywords: ['tired', 'sleep', '困'] },
      { char: '🤤', name_zh: '流口水', name_en: 'drooling face', keywords: ['drool', 'yum', '馋'] },
      { char: '😴', name_zh: '睡觉', name_en: 'sleeping face', keywords: ['sleep', 'zzz', '困', '睡觉'] },
      { char: '😷', name_zh: '戴口罩', name_en: 'face with medical mask', keywords: ['sick', 'mask', '生病'] },
      { char: '🤒', name_zh: '发烧', name_en: 'face with thermometer', keywords: ['sick', 'fever', '发烧'] },
      { char: '🤕', name_zh: '受伤', name_en: 'face with head-bandage', keywords: ['hurt', 'injury', '受伤'] },
      { char: '🤢', name_zh: '恶心', name_en: 'nauseated face', keywords: ['sick', 'vomit', '恶心'] },
      { char: '🤮', name_zh: '呕吐', name_en: 'face vomiting', keywords: ['puke', 'vomit', '吐'] },
      { char: '🤧', name_zh: '打喷嚏', name_en: 'sneezing face', keywords: ['sick', 'sneeze', '感冒'] },
      { char: '🥵', name_zh: '太热了', name_en: 'hot face', keywords: ['heat', 'sweat', '热'] },
      { char: '🥶', name_zh: '太冷了', name_en: 'cold face', keywords: ['cold', 'freeze', '冷'] },
      { char: '🥴', name_zh: '头晕', name_en: 'woozy face', keywords: ['dizzy', 'drunk', '晕'] },
      { char: '😵', name_zh: '头昏眼花', name_en: 'dizzy face', keywords: ['dizzy', '晕'] },
      { char: '🤯', name_zh: '爆炸头', name_en: 'exploding head', keywords: ['mind blown', 'shocked', '震惊', '炸了'] },
      { char: '🤠', name_zh: '牛仔', name_en: 'cowboy hat face', keywords: ['cowboy', 'yeehaw', '牛仔'] },
      { char: '🥳', name_zh: '派对', name_en: 'partying face', keywords: ['party', 'celebration', '庆祝', '狂欢'] },
      { char: '😎', name_zh: '戴墨镜', name_en: 'smiling face with sunglasses', keywords: ['cool', '帅', '酷'] },
      { char: '🤓', name_zh: '书呆子', name_en: 'nerd face', keywords: ['nerd', 'geek', '学霸'] },
      { char: '🧐', name_zh: '戴单片眼镜', name_en: 'face with monocle', keywords: ['classy', 'investigate', '观察'] },
      { char: '😕', name_zh: '困惑', name_en: 'confused face', keywords: ['confused', 'huh', '疑惑'] },
      { char: '😟', name_zh: '担忧', name_en: 'worried face', keywords: ['nervous', 'worry', '担心'] },
      { char: '🙁', name_zh: '微微不满', name_en: 'slightly frowning face', keywords: ['frown', 'sad', '难过'] },
      { char: '☹️', name_zh: '不满', name_en: 'frowning face', keywords: ['sad', 'upset', '生气'] },
      { char: '😮', name_zh: '吃惊', name_en: 'face with open mouth', keywords: ['surprise', 'wow', '惊讶'] },
      { char: '😯', name_zh: '安静', name_en: 'hushed face', keywords: ['surprise', 'wow', '惊讶'] },
      { char: '😲', name_zh: '惊讶', name_en: 'astonished face', keywords: ['shocked', 'wow', '震惊'] },
      { char: '😳', name_zh: '脸红', name_en: 'flushed face', keywords: ['blush', 'shy', '害羞'] },
      { char: '🥺', name_zh: '恳求', name_en: 'pleading face', keywords: ['beg', 'puppy eyes', '可怜'] },
      { char: '😦', name_zh: '皱眉张嘴', name_en: 'frowning face with open mouth', keywords: ['shocked', 'sad', '惊讶'] },
      { char: '😧', name_zh: '极度痛苦', name_en: 'anguished face', keywords: ['shocked', 'pain', '痛苦'] },
      { char: '😨', name_zh: '害怕', name_en: 'fearful face', keywords: ['scared', 'fear', '恐惧'] },
      { char: '😰', name_zh: '焦虑冒汗', name_en: 'anxious face with sweat', keywords: ['nervous', 'sweat', '紧张'] },
      { char: '😥', name_zh: '失望但释然', name_en: 'sad but relieved face', keywords: ['phew', 'sweat', '汗'] },
      { char: '😢', name_zh: '哭泣', name_en: 'crying face', keywords: ['cry', 'sad', '哭'] },
      { char: '😭', name_zh: '大哭', name_en: 'loudly crying face', keywords: ['cry', 'sad', '伤心', '痛苦'] },
      { char: '😱', name_zh: '尖叫', name_en: 'face screaming in fear', keywords: ['scream', 'scared', '惊恐'] },
      { char: '😖', name_zh: '痛苦', name_en: 'confounded face', keywords: ['pain', 'frustrated', '痛苦'] },
      { char: '😣', name_zh: '坚持', name_en: 'persevering face', keywords: ['struggle', '努力'] },
      { char: '😞', name_zh: '失望', name_en: 'disappointed face', keywords: ['sad', '沮丧'] },
      { char: '😓', name_zh: '冷汗', name_en: 'downcast face with sweat', keywords: ['sweat', 'nervous', '汗'] },
      { char: '😩', name_zh: '疲惫', name_en: 'weary face', keywords: ['tired', 'exhausted', '累'] },
      { char: '😫', name_zh: '极度疲惫', name_en: 'tired face', keywords: ['tired', 'exhausted', '累'] },
      { char: '🥱', name_zh: '打哈欠', name_en: 'yawning face', keywords: ['yawn', 'tired', '困'] },
      { char: '😤', name_zh: '傲慢', name_en: 'face with steam from nose', keywords: ['proud', 'mad', '生气'] },
      { char: '😡', name_zh: '发怒', name_en: 'pouting face', keywords: ['mad', 'angry', '愤怒'] },
      { char: '😠', name_zh: '生气', name_en: 'angry face', keywords: ['mad', 'angry', '生气'] },
      { char: '🤬', name_zh: '嘴上带有符号', name_en: 'face with symbols on mouth', keywords: ['swear', 'curse', '骂人'] },
      { char: '😈', name_zh: '微笑的恶魔', name_en: 'smiling face with horns', keywords: ['devil', 'evil', '恶魔'] },
      { char: '👿', name_zh: '生气的恶魔', name_en: 'angry face with horns', keywords: ['devil', 'evil', '恶魔'] },
      { char: '💀', name_zh: '头骨', name_en: 'skull', keywords: ['dead', 'skeleton', '骷髅'] },
      { char: '💩', name_zh: '大便', name_en: 'pile of poo', keywords: ['poop', 'shit', '便便'] },
      { char: '🤡', name_zh: '小丑', name_en: 'clown face', keywords: ['clown', 'fool', '小丑'] },
      { char: '👻', name_zh: '鬼', name_en: 'ghost', keywords: ['spooky', '幽灵'] },
      { char: '👽', name_zh: '外星人', name_en: 'alien', keywords: ['ufo', '外星'] },
      { char: '👾', name_zh: '外星怪物', name_en: 'alien monster', keywords: ['game', '怪物'] },
      { char: '🤖', name_zh: '机器人', name_en: 'robot', keywords: ['bot', 'ai', '机器'] }
    ]
  },
  {
    name: '手势与身体',
    groupIcon: 'Hand',
    emojis: [
      { char: '👋', name_zh: '挥手', name_en: 'waving hand', keywords: ['hello', 'bye', '再见', '你好'] },
      { char: '🤚', name_zh: '手背', name_en: 'raised back of hand', keywords: ['stop', '停'] },
      { char: '🖐️', name_zh: '张开手', name_en: 'hand with fingers splayed', keywords: ['five', '五'] },
      { char: '✋', name_zh: '举手', name_en: 'raised hand', keywords: ['stop', 'high five', '举手'] },
      { char: '🖖', name_zh: '瓦肯举手礼', name_en: 'vulcan salute', keywords: ['spock', 'star trek', '繁荣'] },
      { char: '👌', name_zh: 'OK', name_en: 'OK hand', keywords: ['good', 'yes', '好'] },
      { char: '🤌', name_zh: '捏手指', name_en: 'pinched fingers', keywords: ['italian', '捏'] },
      { char: '🤏', name_zh: '捏', name_en: 'pinching hand', keywords: ['small', '一点点'] },
      { char: '✌️', name_zh: '胜利', name_en: 'victory hand', keywords: ['peace', 'two', '耶'] },
      { char: '🤞', name_zh: '交叉手指', name_en: 'crossed fingers', keywords: ['luck', 'hope', '好运'] },
      { char: '🤟', name_zh: '爱心手势', name_en: 'love-you gesture', keywords: ['love', 'rock', '爱你'] },
      { char: '🤘', name_zh: '摇滚手势', name_en: 'sign of the horns', keywords: ['rock', 'metal', '摇滚'] },
      { char: '🤙', name_zh: '打电话手势', name_en: 'call me hand', keywords: ['shaka', 'phone', '联系'] },
      { char: '👈', name_zh: '向左指', name_en: 'backhand index pointing left', keywords: ['left', '左'] },
      { char: '👉', name_zh: '向右指', name_en: 'backhand index pointing right', keywords: ['right', '右'] },
      { char: '👆', name_zh: '向上指', name_en: 'backhand index pointing up', keywords: ['up', '上'] },
      { char: '👇', name_zh: '向下指', name_en: 'backhand index pointing down', keywords: ['down', '下'] },
      { char: '👍', name_zh: '大拇指', name_en: 'thumbs up', keywords: ['good', 'ok', '赞', '好'] },
      { char: '👎', name_zh: '踩', name_en: 'thumbs down', keywords: ['bad', 'no', '差', '不行'] },
      { char: '✊', name_zh: '拳头', name_en: 'raised fist', keywords: ['power', '加油'] },
      { char: '👊', name_zh: '出拳', name_en: 'oncoming fist', keywords: ['brofist', '击拳'] },
      { char: '🤛', name_zh: '向左出拳', name_en: 'left-facing fist', keywords: ['fist bump', '击拳'] },
      { char: '🤜', name_zh: '向右出拳', name_en: 'right-facing fist', keywords: ['fist bump', '击拳'] },
      { char: '👏', name_zh: '鼓掌', name_en: 'clapping hands', keywords: ['clap', 'applause', '赞赏'] },
      { char: '🙌', name_zh: '举手庆祝', name_en: 'raising hands', keywords: ['celebration', 'hooray', '万岁'] },
      { char: '👐', name_zh: '张开双手', name_en: 'open hands', keywords: ['hug', 'jazz hands', '张开'] },
      { char: '🤲', name_zh: '托举双手', name_en: 'palms up together', keywords: ['pray', '祈祷'] },
      { char: '🤝', name_zh: '握手', name_en: 'handshake', keywords: ['deal', 'agreement', '合作', '成交'] },
      { char: '🙏', name_zh: '双手合十', name_en: 'folded hands', keywords: ['pray', 'please', '祈祷', '拜托'] },
      { char: '✍️', name_zh: '写字', name_en: 'writing hand', keywords: ['write', 'pen', '写'] },
      { char: '💅', name_zh: '涂指甲油', name_en: 'nail polish', keywords: ['beauty', 'sass', '美甲'] },
      { char: '🤳', name_zh: '自拍', name_en: 'selfie', keywords: ['camera', '自拍'] },
      { char: '💪', name_zh: '肌肉', name_en: 'flexed biceps', keywords: ['strong', 'muscle', '力量', '加油'] },
      { char: '🧠', name_zh: '大脑', name_en: 'brain', keywords: ['smart', 'think', '智慧', '脑'] },
      { char: '🫀', name_zh: '心脏', name_en: 'anatomical heart', keywords: ['heart', '器官'] },
      { char: '🫁', name_zh: '肺', name_en: 'lungs', keywords: ['breathe', '呼吸'] },
      { char: '🦷', name_zh: '牙齿', name_en: 'tooth', keywords: ['dentist', '牙'] },
      { char: '🦴', name_zh: '骨头', name_en: 'bone', keywords: ['skeleton', '骨'] },
      { char: '👀', name_zh: '双眼', name_en: 'eyes', keywords: ['look', 'see', '看', '关注'] },
      { char: '👁️', name_zh: '眼睛', name_en: 'eye', keywords: ['look', 'vision', '眼'] },
      { char: '👅', name_zh: '舌头', name_en: 'tongue', keywords: ['taste', '舌'] },
      { char: '👄', name_zh: '嘴巴', name_en: 'mouth', keywords: ['lips', 'kiss', '嘴'] }
    ]
  },
  {
    name: '动物与自然',
    groupIcon: 'Cat',
    emojis: [
      { char: '🐶', name_zh: '狗', name_en: 'dog', keywords: ['pet', 'puppy', '狗狗', '宠物'] },
      { char: '🐱', name_zh: '猫', name_en: 'cat', keywords: ['pet', 'kitten', '猫咪', '小猫'] },
      { char: '🐭', name_zh: '老鼠', name_en: 'mouse', keywords: ['rodent', '耗子'] },
      { char: '🐹', name_zh: '仓鼠', name_en: 'hamster', keywords: ['pet'] },
      { char: '🐰', name_zh: '兔子', name_en: 'rabbit', keywords: ['bunny'] },
      { char: '🦊', name_zh: '狐狸', name_en: 'fox', keywords: ['animal'] },
      { char: '🐻', name_zh: '熊', name_en: 'bear', keywords: ['wild'] },
      { char: '🐼', name_zh: '熊猫', name_en: 'panda', keywords: ['国宝'] },
      { char: '🐻‍❄️', name_zh: '北极熊', name_en: 'polar bear', keywords: ['cold', 'bear'] },
      { char: '🐨', name_zh: '考拉', name_en: 'koala', keywords: ['australia'] },
      { char: '🐯', name_zh: '老虎', name_en: 'tiger', keywords: ['wildcat'] },
      { char: '🦁', name_zh: '狮子', name_en: 'lion', keywords: ['king'] },
      { char: '🐮', name_zh: '牛', name_en: 'cow', keywords: ['moo'] },
      { char: '🐷', name_zh: '猪', name_en: 'pig', keywords: ['oink'] },
      { char: '🐸', name_zh: '青蛙', name_en: 'frog', keywords: ['toad', '蛤蟆'] },
      { char: '🐵', name_zh: '猴子', name_en: 'monkey', keywords: ['ape', '猕猴'] },
      { char: '🙈', name_zh: '非礼勿视', name_en: 'see no evil monkey', keywords: ['blind', '捂眼睛'] },
      { char: '🙉', name_zh: '非礼勿听', name_en: 'hear no evil monkey', keywords: ['deaf', '捂耳朵'] },
      { char: '🙊', name_zh: '非礼勿言', name_en: 'speak no evil monkey', keywords: ['mute', '捂嘴巴'] },
      { char: '🐒', name_zh: '猴子', name_en: 'monkey', keywords: ['ape'] },
      { char: '🐔', name_zh: '鸡', name_en: 'chicken', keywords: ['cluck'] },
      { char: '🐧', name_zh: '企鹅', name_en: 'penguin', keywords: ['bird', 'ice'] },
      { char: '🐦', name_zh: '鸟', name_en: 'bird', keywords: ['tweet'] },
      { char: '🐤', name_zh: '小鸡', name_en: 'baby chick', keywords: ['yellow'] },
      { char: '🐣', name_zh: '破壳而出的小鸡', name_en: 'hatching chick', keywords: ['egg', 'hatch'] },
      { char: '🐥', name_zh: '正面小鸡', name_en: 'front-facing baby chick', keywords: ['bird'] },
      { char: '🦆', name_zh: '鸭子', name_en: 'duck', keywords: ['quack'] },
      { char: '🦅', name_zh: '老鹰', name_en: 'eagle', keywords: ['bird of prey'] },
      { char: '🦉', name_zh: '猫头鹰', name_en: 'owl', keywords: ['hoot', 'wise'] },
      { char: '🦇', name_zh: '蝙蝠', name_en: 'bat', keywords: ['vampire'] },
      { char: '🐺', name_zh: '狼', name_en: 'wolf', keywords: ['howl'] },
      { char: '🐗', name_zh: '野猪', name_en: 'boar', keywords: ['pig'] },
      { char: '🐴', name_zh: '马', name_en: 'horse', keywords: ['gallop'] },
      { char: '🦄', name_zh: '独角兽', name_en: 'unicorn', keywords: ['magic'] },
      { char: '🐝', name_zh: '蜜蜂', name_en: 'honeybee', keywords: ['bug', 'honey'] },
      { char: '🐛', name_zh: '毛毛虫', name_en: 'bug', keywords: ['insect'] },
      { char: '🦋', name_zh: '蝴蝶', name_en: 'butterfly', keywords: ['insect', 'beautiful'] },
      { char: '🐌', name_zh: '蜗牛', name_en: 'snail', keywords: ['slow'] },
      { char: '🐞', name_zh: '瓢虫', name_en: 'lady beetle', keywords: ['bug', 'luck'] },
      { char: '🐜', name_zh: '蚂蚁', name_en: 'ant', keywords: ['insect'] },
      { char: '🕷️', name_zh: '蜘蛛', name_en: 'spider', keywords: ['web'] },
      { char: '🐢', name_zh: '乌龟', name_en: 'turtle', keywords: ['slow'] },
      { char: '🐍', name_zh: '蛇', name_en: 'snake', keywords: ['hiss'] },
      { char: '🦎', name_zh: '蜥蜴', name_en: 'lizard', keywords: ['reptile'] },
      { char: '🦖', name_zh: '霸王龙', name_en: 'T-Rex', keywords: ['dinosaur'] },
      { char: '🦕', name_zh: '蜥脚类恐龙', name_en: 'sauropod', keywords: ['dinosaur'] },
      { char: '🐙', name_zh: '章鱼', name_en: 'octopus', keywords: ['ocean'] },
      { char: '🦑', name_zh: '乌贼', name_en: 'squid', keywords: ['ocean'] },
      { char: '🦐', name_zh: '虾', name_en: 'shrimp', keywords: ['ocean'] },
      { char: '🦞', name_zh: '龙虾', name_en: 'lobster', keywords: ['ocean'] },
      { char: '🦀', name_zh: '螃蟹', name_en: 'crab', keywords: ['ocean'] },
      { char: '🐡', name_zh: '河豚', name_en: 'blowfish', keywords: ['ocean'] },
      { char: '🐠', name_zh: '热带鱼', name_en: 'tropical fish', keywords: ['ocean'] },
      { char: '🐟', name_zh: '鱼', name_en: 'fish', keywords: ['ocean'] },
      { char: '🐬', name_zh: '海豚', name_en: 'dolphin', keywords: ['ocean'] },
      { char: '🐳', name_zh: '喷水的鲸鱼', name_en: 'spouting whale', keywords: ['ocean'] },
      { char: '🐋', name_zh: '鲸鱼', name_en: 'whale', keywords: ['ocean'] },
      { char: '🦈', name_zh: '鲨鱼', name_en: 'shark', keywords: ['ocean'] },
      { char: '🐊', name_zh: '鳄鱼', name_en: 'crocodile', keywords: ['reptile'] },
      { char: '🐅', name_zh: '老虎', name_en: 'tiger', keywords: ['wildcat'] },
      { char: '🐆', name_zh: '豹', name_en: 'leopard', keywords: ['wildcat'] },
      { char: '🦓', name_zh: '斑马', name_en: 'zebra', keywords: ['stripe'] },
      { char: '🦍', name_zh: '大猩猩', name_en: 'gorilla', keywords: ['ape'] },
      { char: '🦧', name_zh: '红毛猩猩', name_en: 'orangutan', keywords: ['ape'] },
      { char: '🐘', name_zh: '大象', name_en: 'elephant', keywords: ['trunk'] },
      { char: '🦛', name_zh: '河马', name_en: 'hippopotamus', keywords: ['water'] },
      { char: '🦏', name_zh: '犀牛', name_en: 'rhinoceros', keywords: ['horn'] },
      { char: '🐪', name_zh: '单峰骆驼', name_en: 'camel', keywords: ['desert'] },
      { char: '🐫', name_zh: '双峰骆驼', name_en: 'two-hump camel', keywords: ['desert'] },
      { char: '🦒', name_zh: '长颈鹿', name_en: 'giraffe', keywords: ['tall'] },
      { char: '🦘', name_zh: '袋鼠', name_en: 'kangaroo', keywords: ['jump'] },
      { char: '🐃', name_zh: '水牛', name_en: 'water buffalo', keywords: ['ox'] },
      { char: '🐂', name_zh: '公牛', name_en: 'ox', keywords: ['cow'] },
      { char: '🐄', name_zh: '奶牛', name_en: 'cow', keywords: ['moo'] },
      { char: '🐎', name_zh: '马', name_en: 'horse', keywords: ['gallop'] },
      { char: '🐖', name_zh: '猪', name_en: 'pig', keywords: ['oink'] },
      { char: '🐏', name_zh: '公羊', name_en: 'ram', keywords: ['sheep'] },
      { char: '🐑', name_zh: '绵羊', name_en: 'ewe', keywords: ['sheep'] },
      { char: '🦙', name_zh: '羊驼', name_en: 'llama', keywords: ['alpaca'] },
      { char: '🐐', name_zh: '山羊', name_en: 'goat', keywords: ['horns'] },
      { char: '🦌', name_zh: '鹿', name_en: 'deer', keywords: ['antlers'] },
      { char: '🐕', name_zh: '狗', name_en: 'dog', keywords: ['pet'] },
      { char: '🐩', name_zh: '贵宾犬', name_en: 'poodle', keywords: ['dog'] },
      { char: '🦮', name_zh: '导盲犬', name_en: 'guide dog', keywords: ['blind'] },
      { char: '🐕‍🦺', name_zh: '服务犬', name_en: 'service dog', keywords: ['help'] },
      { char: '🐈', name_zh: '猫', name_en: 'cat', keywords: ['pet'] },
      { char: '🐓', name_zh: '公鸡', name_en: 'rooster', keywords: ['morning'] },
      { char: '🦃', name_zh: '火鸡', name_en: 'turkey', keywords: ['thanksgiving'] },
      { char: '🦚', name_zh: '孔雀', name_en: 'peacock', keywords: ['bird'] },
      { char: '🦜', name_zh: '鹦鹉', name_en: 'parrot', keywords: ['bird'] },
      { char: '🦢', name_zh: '天鹅', name_en: 'swan', keywords: ['bird'] },
      { char: '🦩', name_zh: '火烈鸟', name_en: 'flamingo', keywords: ['bird'] },
      { char: '🕊️', name_zh: '鸽子', name_en: 'dove', keywords: ['peace'] },
      { char: '🐇', name_zh: '兔子', name_en: 'rabbit', keywords: ['bunny'] },
      { char: '🦝', name_zh: '浣熊', name_en: 'raccoon', keywords: ['trash panda'] },
      { char: '🦨', name_zh: '臭鼬', name_en: 'skunk', keywords: ['stink'] },
      { char: '🦡', name_zh: '獾', name_en: 'badger', keywords: ['honey badger'] },
      { char: '🦦', name_zh: '水獭', name_en: 'otter', keywords: ['water'] },
      { char: '🦥', name_zh: '树懒', name_en: 'sloth', keywords: ['slow'] },
      { char: '🐁', name_zh: '老鼠', name_en: 'mouse', keywords: ['rodent'] },
      { char: '🐀', name_zh: '大老鼠', name_en: 'rat', keywords: ['rodent'] },
      { char: '🐿️', name_zh: '花栗鼠', name_en: 'chipmunk', keywords: ['squirrel'] },
      { char: '🦔', name_zh: '刺猬', name_en: 'hedgehog', keywords: ['spikes'] },
      { char: '🌳', name_zh: '树', name_en: 'deciduous tree', keywords: ['wood', 'nature', '森林'] },
      { char: '🌲', name_zh: '松树', name_en: 'evergreen tree', keywords: ['wood', 'nature', '森林'] },
      { char: '🌴', name_zh: '棕榈树', name_en: 'palm tree', keywords: ['wood', 'nature', '沙滩'] },
      { char: '🌵', name_zh: '仙人掌', name_en: 'cactus', keywords: ['desert', '沙漠'] },
      { char: '🌸', name_zh: '樱花', name_en: 'cherry blossom', keywords: ['flower', 'spring', '花', '春天'] },
      { char: '🌺', name_zh: '木槿', name_en: 'hibiscus', keywords: ['flower', '花'] },
      { char: '🌻', name_zh: '向日葵', name_en: 'sunflower', keywords: ['flower', '花'] },
      { char: '🌼', name_zh: '开花', name_en: 'blossom', keywords: ['flower', '花'] },
      { char: '🌷', name_zh: '郁金香', name_en: 'tulip', keywords: ['flower', '花'] },
      { char: '🌹', name_zh: '玫瑰', name_en: 'rose', keywords: ['flower', '花'] },
      { char: '🥀', name_zh: '枯萎的花', name_en: 'wilted flower', keywords: ['flower', 'sad', '凋零'] },
      { char: '☘️', name_zh: '三叶草', name_en: 'shamrock', keywords: ['luck', 'lucky'] },
      { char: '🍀', name_zh: '四叶草', name_en: 'four leaf clover', keywords: ['luck', 'lucky'] },
      { char: '🍁', name_zh: '枫叶', name_en: 'maple leaf', keywords: ['autumn', 'fall'] },
      { char: '🍂', name_zh: '落叶', name_en: 'fallen leaf', keywords: ['autumn', 'fall'] },
      { char: '🍃', name_zh: '风中飘落的叶子', name_en: 'leaf fluttering in wind', keywords: ['wind', 'leaf'] },
      { char: '🍄', name_zh: '蘑菇', name_en: 'mushroom', keywords: ['fungus'] },
      { char: '🌰', name_zh: '栗子', name_en: 'chestnut', keywords: ['nut'] },
      { char: '✨', name_zh: '闪光', name_en: 'sparkles', keywords: ['star', 'magic', '闪耀', '魔法'] },
      { char: '🔥', name_zh: '火', name_en: 'fire', keywords: ['hot', 'flame', '热', '火爆'] },
      { char: '⭐', name_zh: '星星', name_en: 'star', keywords: ['favorite', '收藏', '星'] },
      { char: '🌟', name_zh: '闪耀的星星', name_en: 'glowing star', keywords: ['shine', '出色'] },
      { char: '⚡', name_zh: '闪电', name_en: 'high voltage', keywords: ['electric', 'lightning', '快', '雷电'] },
      { char: '☀️', name_zh: '太阳', name_en: 'sun', keywords: ['weather', 'sunny', '晴天'] },
      { char: '⛅', name_zh: '多云', name_en: 'sun behind cloud', keywords: ['weather', 'cloudy'] },
      { char: '☁️', name_zh: '云', name_en: 'cloud', keywords: ['weather', 'cloudy'] },
      { char: '🌧️', name_zh: '下雨', name_en: 'cloud with rain', keywords: ['weather', 'rain', '雨天'] },
      { char: '❄️', name_zh: '雪花', name_en: 'snowflake', keywords: ['weather', 'snow', '雪'] },
      { char: '⛄', name_zh: '雪人', name_en: 'snowman', keywords: ['weather', 'snow', '冬'] },
      { char: '🌊', name_zh: '海浪', name_en: 'water wave', keywords: ['ocean', 'sea', '水'] },
      { char: '💧', name_zh: '水滴', name_en: 'droplet', keywords: ['water', 'rain'] }
    ]
  },
  {
    name: '食物与饮料',
    groupIcon: 'Coffee',
    emojis: [
      { char: '🍎', name_zh: '红苹果', name_en: 'red apple', keywords: ['fruit', '水果'] },
      { char: '🍏', name_zh: '青苹果', name_en: 'green apple', keywords: ['fruit', '水果'] },
      { char: '🍐', name_zh: '梨', name_en: 'pear', keywords: ['fruit', '水果'] },
      { char: '🍊', name_zh: '橘子', name_en: 'tangerine', keywords: ['fruit', '水果'] },
      { char: '🍋', name_zh: '柠檬', name_en: 'lemon', keywords: ['fruit', '水果'] },
      { char: '🍌', name_zh: '香蕉', name_en: 'banana', keywords: ['fruit', '水果'] },
      { char: '🍉', name_zh: '西瓜', name_en: 'watermelon', keywords: ['fruit', '水果'] },
      { char: '🍇', name_zh: '葡萄', name_en: 'grapes', keywords: ['fruit', '水果'] },
      { char: '🍓', name_zh: '草莓', name_en: 'strawberry', keywords: ['fruit', '水果'] },
      { char: '🍈', name_zh: '哈密瓜', name_en: 'melon', keywords: ['fruit', '水果'] },
      { char: '🍒', name_zh: '樱桃', name_en: 'cherries', keywords: ['fruit', '水果'] },
      { char: '🍑', name_zh: '桃子', name_en: 'peach', keywords: ['fruit', '水果'] },
      { char: '🥭', name_zh: '芒果', name_en: 'mango', keywords: ['fruit', '水果'] },
      { char: '🍍', name_zh: '菠萝', name_en: 'pineapple', keywords: ['fruit', '水果'] },
      { char: '🥥', name_zh: '椰子', name_en: 'coconut', keywords: ['fruit', '水果'] },
      { char: '🥝', name_zh: '猕猴桃', name_en: 'kiwi fruit', keywords: ['fruit', '水果'] },
      { char: '🍅', name_zh: '西红柿', name_en: 'tomato', keywords: ['fruit', 'veggie', '蔬菜'] },
      { char: '🍆', name_zh: '茄子', name_en: 'eggplant', keywords: ['veggie', '蔬菜'] },
      { char: '🥑', name_zh: '牛油果', name_en: 'avocado', keywords: ['fruit', 'veggie', '蔬菜'] },
      { char: '🥦', name_zh: '西兰花', name_en: 'broccoli', keywords: ['veggie', '蔬菜'] },
      { char: '🥬', name_zh: '绿叶蔬菜', name_en: 'leafy green', keywords: ['veggie', '蔬菜'] },
      { char: '🥒', name_zh: '黄瓜', name_en: 'cucumber', keywords: ['veggie', '蔬菜'] },
      { char: '🌶️', name_zh: '红辣椒', name_en: 'hot pepper', keywords: ['spicy', '辣椒'] },
      { char: '🌽', name_zh: '玉米', name_en: 'ear of corn', keywords: ['veggie', '蔬菜'] },
      { char: '🥕', name_zh: '胡萝卜', name_en: 'carrot', keywords: ['veggie', '蔬菜'] },
      { char: '🧄', name_zh: '大蒜', name_en: 'garlic', keywords: ['veggie', '蔬菜'] },
      { char: '🧅', name_zh: '洋葱', name_en: 'onion', keywords: ['veggie', '蔬菜'] },
      { char: '🥔', name_zh: '土豆', name_en: 'potato', keywords: ['veggie', '蔬菜'] },
      { char: '🍠', name_zh: '烤地瓜', name_en: 'roasted sweet potato', keywords: ['veggie', '蔬菜'] },
      { char: '🥐', name_zh: '牛角面包', name_en: 'croissant', keywords: ['bread', '面包'] },
      { char: '🍞', name_zh: '面包', name_en: 'bread', keywords: ['food'] },
      { char: '🥖', name_zh: '法棍', name_en: 'baguette bread', keywords: ['bread', '面包'] },
      { char: '🥨', name_zh: '椒盐卷饼', name_en: 'pretzel', keywords: ['bread', '面包'] },
      { char: '🧀', name_zh: '奶酪', name_en: 'cheese wedge', keywords: ['food'] },
      { char: '🥚', name_zh: '鸡蛋', name_en: 'egg', keywords: ['food'] },
      { char: '🍳', name_zh: '煎蛋', name_en: 'cooking', keywords: ['food', 'breakfast'] },
      { char: '🥞', name_zh: '薄煎饼', name_en: 'pancakes', keywords: ['food', 'breakfast'] },
      { char: '🧇', name_zh: '华夫饼', name_en: 'waffle', keywords: ['food', 'breakfast'] },
      { char: '🥓', name_zh: '培根', name_en: 'bacon', keywords: ['food', 'meat'] },
      { char: '🥩', name_zh: '肉块', name_en: 'cut of meat', keywords: ['food', 'meat'] },
      { char: '🍗', name_zh: '家禽腿', name_en: 'poultry leg', keywords: ['food', 'meat'] },
      { char: '🍖', name_zh: '带骨肉', name_en: 'meat on bone', keywords: ['food', 'meat'] },
      { char: '🌭', name_zh: '热狗', name_en: 'hot dog', keywords: ['food', 'fast food'] },
      { char: '🍔', name_zh: '汉堡', name_en: 'hamburger', keywords: ['fast food', '汉堡包'] },
      { char: '🍟', name_zh: '薯条', name_en: 'french fries', keywords: ['fast food', 'food'] },
      { char: '🍕', name_zh: '比萨', name_en: 'pizza', keywords: ['food', '披萨'] },
      { char: '🥪', name_zh: '三明治', name_en: 'sandwich', keywords: ['food', 'lunch'] },
      { char: '🥙', name_zh: '夹肉大饼', name_en: 'stuffed flatbread', keywords: ['food', 'kebab'] },
      { char: '🧆', name_zh: '沙拉三明治', name_en: 'falafel', keywords: ['food'] },
      { char: '🌮', name_zh: '夹饼', name_en: 'taco', keywords: ['mexican'] },
      { char: '🌯', name_zh: '墨西哥卷饼', name_en: 'burrito', keywords: ['mexican'] },
      { char: '🥗', name_zh: '绿色沙拉', name_en: 'green salad', keywords: ['healthy', '蔬菜'] },
      { char: '🥘', name_zh: '装有食物的浅底锅', name_en: 'shallow pan of food', keywords: ['paella', 'food'] },
      { char: '🥫', name_zh: '罐头食品', name_en: 'canned food', keywords: ['soup'] },
      { char: '🍝', name_zh: '意大利面', name_en: 'spaghetti', keywords: ['pasta', 'food'] },
      { char: '🍜', name_zh: '面条', name_en: 'steaming bowl', keywords: ['ramen', 'noodle'] },
      { char: '🍲', name_zh: '炖菜', name_en: 'pot of food', keywords: ['stew', 'soup'] },
      { char: '🍛', name_zh: '咖喱饭', name_en: 'curry rice', keywords: ['food'] },
      { char: '🍣', name_zh: '寿司', name_en: 'sushi', keywords: ['japanese', '日料'] },
      { char: '🍱', name_zh: '便当', name_en: 'bento box', keywords: ['japanese', 'food'] },
      { char: '🥟', name_zh: '饺子', name_en: 'dumpling', keywords: ['food'] },
      { char: '🦪', name_zh: '生蚝', name_en: 'oyster', keywords: ['seafood'] },
      { char: '🍤', name_zh: '炸虾', name_en: 'fried shrimp', keywords: ['seafood', 'tempura'] },
      { char: '🍙', name_zh: '饭团', name_en: 'rice ball', keywords: ['japanese', 'food'] },
      { char: '🍚', name_zh: '米饭', name_en: 'cooked rice', keywords: ['food'] },
      { char: '🍘', name_zh: '米饼', name_en: 'rice cracker', keywords: ['japanese', 'snack'] },
      { char: '🍥', name_zh: '鱼板', name_en: 'fish cake with swirl', keywords: ['japanese', 'ramen'] },
      { char: '🥠', name_zh: '幸运饼干', name_en: 'fortune cookie', keywords: ['cookie', 'luck'] },
      { char: '🥮', name_zh: '月饼', name_en: 'moon cake', keywords: ['autumn', 'festival'] },
      { char: '🍢', name_zh: '关东煮', name_en: 'oden', keywords: ['japanese', 'food'] },
      { char: '🍡', name_zh: '三色丸子', name_en: 'dango', keywords: ['japanese', 'sweet'] },
      { char: '🍧', name_zh: '刨冰', name_en: 'shaved ice', keywords: ['dessert', 'sweet'] },
      { char: '🍨', name_zh: '冰淇淋', name_en: 'ice cream', keywords: ['dessert', 'sweet'] },
      { char: '🍦', name_zh: '冰淇淋蛋筒', name_en: 'soft ice cream', keywords: ['dessert', '甜点'] },
      { char: '🥧', name_zh: '派', name_en: 'pie', keywords: ['dessert', 'sweet'] },
      { char: '🍰', name_zh: '蛋糕', name_en: 'shortcake', keywords: ['dessert', 'sweet'] },
      { char: '🧁', name_zh: '纸杯蛋糕', name_en: 'cupcake', keywords: ['dessert', 'sweet'] },
      { char: '🎂', name_zh: '生日蛋糕', name_en: 'birthday cake', keywords: ['party', '生日'] },
      { char: '🍮', name_zh: '布丁', name_en: 'custard', keywords: ['dessert', 'sweet'] },
      { char: '🍭', name_zh: '棒棒糖', name_en: 'lollipop', keywords: ['candy', 'sweet'] },
      { char: '🍬', name_zh: '糖果', name_en: 'candy', keywords: ['sweet'] },
      { char: '🍫', name_zh: '巧克力', name_en: 'chocolate bar', keywords: ['sweet'] },
      { char: '🍿', name_zh: '爆米花', name_en: 'popcorn', keywords: ['movie', 'snack'] },
      { char: '🍩', name_zh: '甜甜圈', name_en: 'doughnut', keywords: ['dessert', 'sweet'] },
      { char: '🍪', name_zh: '饼干', name_en: 'cookie', keywords: ['snack', 'sweet'] },
      { char: '🥛', name_zh: '牛奶', name_en: 'glass of milk', keywords: ['drink'] },
      { char: '🍼', name_zh: '奶瓶', name_en: 'baby bottle', keywords: ['drink', 'baby'] },
      { char: '☕', name_zh: '热饮', name_en: 'hot beverage', keywords: ['coffee', '咖啡', '茶'] },
      { char: '🍵', name_zh: '热茶', name_en: 'teacup without handle', keywords: ['tea', 'drink'] },
      { char: '🧃', name_zh: '果汁饮料', name_en: 'beverage box', keywords: ['juice', 'drink'] },
      { char: '🥤', name_zh: '带吸管杯', name_en: 'cup with straw', keywords: ['drink', 'soda'] },
      { char: '🧋', name_zh: '珍珠奶茶', name_en: 'bubble tea', keywords: ['boba', 'drink'] },
      { char: '🍶', name_zh: '清酒', name_en: 'sake', keywords: ['drink', 'japanese'] },
      { char: '🍺', name_zh: '啤酒', name_en: 'beer mug', keywords: ['drink', 'alcohol', '酒'] },
      { char: '🍻', name_zh: '干杯', name_en: 'clinking beer mugs', keywords: ['cheers', 'drink'] },
      { char: '🥂', name_zh: '碰杯', name_en: 'clinking glasses', keywords: ['cheers', '干杯'] },
      { char: '🍷', name_zh: '葡萄酒', name_en: 'wine glass', keywords: ['drink', 'alcohol'] },
      { char: '🥃', name_zh: '烈酒', name_en: 'tumbler glass', keywords: ['drink', 'alcohol'] },
      { char: '🍸', name_zh: '鸡尾酒', name_en: 'cocktail glass', keywords: ['drink', 'alcohol'] },
      { char: '🍹', name_zh: '热带饮料', name_en: 'tropical drink', keywords: ['drink', 'alcohol'] },
      { char: '🧉', name_zh: '马黛茶', name_en: 'mate', keywords: ['drink'] },
      { char: '🍾', name_zh: '香槟', name_en: 'bottle with popping cork', keywords: ['party', 'celebration'] },
      { char: '🧊', name_zh: '冰块', name_en: 'ice', keywords: ['cold'] }
    ]
  },
  {
    name: '活动与运动',
    groupIcon: 'Activity',
    emojis: [
      { char: '⚽', name_zh: '足球', name_en: 'soccer ball', keywords: ['sports', 'football'] },
      { char: '🏀', name_zh: '篮球', name_en: 'basketball', keywords: ['sports'] },
      { char: '🏈', name_zh: '美式橄榄球', name_en: 'american football', keywords: ['sports'] },
      { char: '⚾', name_zh: '棒球', name_en: 'baseball', keywords: ['sports'] },
      { char: '🥎', name_zh: '垒球', name_en: 'softball', keywords: ['sports'] },
      { char: '🎾', name_zh: '网球', name_en: 'tennis', keywords: ['sports'] },
      { char: '🏐', name_zh: '排球', name_en: 'volleyball', keywords: ['sports'] },
      { char: '🏉', name_zh: '橄榄球', name_en: 'rugby football', keywords: ['sports'] },
      { char: '🥏', name_zh: '飞盘', name_en: 'flying disc', keywords: ['sports'] },
      { char: '🎱', name_zh: '台球', name_en: 'pool 8 ball', keywords: ['sports', 'billiards'] },
      { char: '🪀', name_zh: '溜溜球', name_en: 'yo-yo', keywords: ['toy'] },
      { char: '🏓', name_zh: '乒乓球', name_en: 'ping pong', keywords: ['sports'] },
      { char: '🏸', name_zh: '羽毛球', name_en: 'badminton', keywords: ['sports'] },
      { char: '🏒', name_zh: '冰球', name_en: 'ice hockey', keywords: ['sports'] },
      { char: '🏑', name_zh: '曲棍球', name_en: 'field hockey', keywords: ['sports'] },
      { char: '🥍', name_zh: '长曲棍球', name_en: 'lacrosse', keywords: ['sports'] },
      { char: '🏏', name_zh: '板球', name_en: 'cricket', keywords: ['sports'] },
      { char: '🪃', name_zh: '回旋镖', name_en: 'boomerang', keywords: ['sports'] },
      { char: '🥅', name_zh: '球门', name_en: 'goal net', keywords: ['sports'] },
      { char: '⛳', name_zh: '高尔夫', name_en: 'golf', keywords: ['sports'] },
      { char: '🪁', name_zh: '风筝', name_en: 'kite', keywords: ['fly'] },
      { char: '🏹', name_zh: '弓箭', name_en: 'bow and arrow', keywords: ['sports'] },
      { char: '🎣', name_zh: '钓鱼', name_en: 'fishing pole', keywords: ['sports'] },
      { char: '🤿', name_zh: '潜水面罩', name_en: 'diving mask', keywords: ['swim', 'ocean'] },
      { char: '🥊', name_zh: '拳击手套', name_en: 'boxing glove', keywords: ['sports'] },
      { char: '🥋', name_zh: '武术服', name_en: 'martial arts uniform', keywords: ['sports', 'judo', 'karate'] },
      { char: '🎽', name_zh: '运动背心', name_en: 'running shirt', keywords: ['sports'] },
      { char: '🛹', name_zh: '滑板', name_en: 'skateboard', keywords: ['sports'] },
      { char: '🛼', name_zh: '轮滑', name_en: 'roller skate', keywords: ['sports'] },
      { char: '🛷', name_zh: '雪橇', name_en: 'sled', keywords: ['winter', 'sports'] },
      { char: '⛸️', name_zh: '滑冰', name_en: 'ice skate', keywords: ['winter', 'sports'] },
      { char: '🎿', name_zh: '滑雪板', name_en: 'skis', keywords: ['winter', 'sports'] },
      { char: '⛷️', name_zh: '滑雪者', name_en: 'skier', keywords: ['winter', 'sports'] },
      { char: '🏂', name_zh: '单板滑雪', name_en: 'snowboarder', keywords: ['winter', 'sports'] },
      { char: '🏋️', name_zh: '举重', name_en: 'person lifting weights', keywords: ['gym', 'workout'] },
      { char: '🤼', name_zh: '摔跤', name_en: 'people wrestling', keywords: ['sports'] },
      { char: '🤸', name_zh: '翻筋斗', name_en: 'person cartwheeling', keywords: ['gymnastics'] },
      { char: '⛹️', name_zh: '打篮球', name_en: 'person bouncing ball', keywords: ['sports'] },
      { char: '🤺', name_zh: '击剑', name_en: 'person fencing', keywords: ['sports'] },
      { char: '🤾', name_zh: '玩手球', name_en: 'person playing handball', keywords: ['sports'] },
      { char: '🏌️', name_zh: '打高尔夫', name_en: 'person golfing', keywords: ['sports'] },
      { char: '🏇', name_zh: '赛马', name_en: 'horse racing', keywords: ['sports'] },
      { char: '🧘', name_zh: '瑜伽', name_en: 'person in lotus position', keywords: ['meditation', 'relax'] },
      { char: '🏄', name_zh: '冲浪', name_en: 'person surfing', keywords: ['ocean', 'sports'] },
      { char: '🏊', name_zh: '游泳', name_en: 'person swimming', keywords: ['water', 'sports'] },
      { char: '🤽', name_zh: '水球', name_en: 'person playing water polo', keywords: ['water', 'sports'] },
      { char: '🚣', name_zh: '划船', name_en: 'person rowing boat', keywords: ['water', 'sports'] },
      { char: '🧗', name_zh: '攀岩', name_en: 'person climbing', keywords: ['sports'] },
      { char: '🚵', name_zh: '山地自行车', name_en: 'person mountain biking', keywords: ['sports'] },
      { char: '🚴', name_zh: '骑自行车', name_en: 'person biking', keywords: ['sports'] },
      { char: '🏆', name_zh: '奖杯', name_en: 'trophy', keywords: ['win', 'award', '胜利', '奖励'] },
      { char: '🥇', name_zh: '金牌', name_en: '1st place medal', keywords: ['win', 'award', 'first'] },
      { char: '🥈', name_zh: '银牌', name_en: '2nd place medal', keywords: ['award', 'second'] },
      { char: '🥉', name_zh: '铜牌', name_en: '3rd place medal', keywords: ['award', 'third'] },
      { char: '🏅', name_zh: '奖牌', name_en: 'sports medal', keywords: ['award'] },
      { char: '🎖️', name_zh: '军功章', name_en: 'military medal', keywords: ['award'] },
      { char: '🏵️', name_zh: '花结', name_en: 'rosette', keywords: ['award'] },
      { char: '🎗️', name_zh: '黄丝带', name_en: 'reminder ribbon', keywords: ['award'] },
      { char: '🎫', name_zh: '门票', name_en: 'ticket', keywords: ['event'] },
      { char: '🎟️', name_zh: '入场券', name_en: 'admission tickets', keywords: ['event'] },
      { char: '🎪', name_zh: '马戏团帐篷', name_en: 'circus tent', keywords: ['event'] },
      { char: '🤹', name_zh: '杂耍', name_en: 'person juggling', keywords: ['event'] },
      { char: '🎭', name_zh: '面具', name_en: 'performing arts', keywords: ['event', 'theater'] },
      { char: '🩰', name_zh: '芭蕾舞鞋', name_en: 'ballet shoes', keywords: ['dance'] },
      { char: '🎨', name_zh: '调色板', name_en: 'artist palette', keywords: ['art', 'design', '艺术', '设计'] },
      { char: '🎬', name_zh: '场记板', name_en: 'clapper board', keywords: ['movie', 'film', '电影', '视频'] },
      { char: '🎤', name_zh: '麦克风', name_en: 'microphone', keywords: ['sing', 'karaoke', '唱歌', '录音'] },
      { char: '🎧', name_zh: '耳机', name_en: 'headphone', keywords: ['music', 'listen', '音乐', '听'] },
      { char: '🎼', name_zh: '乐谱', name_en: 'musical score', keywords: ['music'] },
      { char: '🎹', name_zh: '钢琴', name_en: 'musical keyboard', keywords: ['music', 'instrument'] },
      { char: '🥁', name_zh: '鼓', name_en: 'drum', keywords: ['music', 'instrument'] },
      { char: '🎷', name_zh: '萨克斯', name_en: 'saxophone', keywords: ['music', 'instrument'] },
      { char: '🎺', name_zh: '小号', name_en: 'trumpet', keywords: ['music', 'instrument'] },
      { char: '🎸', name_zh: '吉他', name_en: 'guitar', keywords: ['music', 'instrument'] },
      { char: '🪕', name_zh: '班卓琴', name_en: 'banjo', keywords: ['music', 'instrument'] },
      { char: '🎻', name_zh: '小提琴', name_en: 'violin', keywords: ['music', 'instrument'] },
      { char: '🎲', name_zh: '骰子', name_en: 'game die', keywords: ['game', 'casino'] },
      { char: '♟️', name_zh: '国际象棋', name_en: 'chess pawn', keywords: ['game', 'strategy'] },
      { char: '🎯', name_zh: '正中靶心', name_en: 'direct hit', keywords: ['target', 'goal', '目标', '准确'] },
      { char: '🎳', name_zh: '保龄球', name_en: 'bowling', keywords: ['sports'] },
      { char: '🎮', name_zh: '游戏手柄', name_en: 'video game', keywords: ['play', 'console', '打游戏'] },
      { char: '🎰', name_zh: '老虎机', name_en: 'slot machine', keywords: ['game', 'casino'] },
      { char: '🧩', name_zh: '拼图', name_en: 'puzzle piece', keywords: ['game'] }
    ]
  },
  {
    name: '物体',
    groupIcon: 'Lightbulb',
    emojis: [
      { char: '💻', name_zh: '笔记本电脑', name_en: 'laptop', keywords: ['computer', 'pc', '电脑'] },
      { char: '🖥️', name_zh: '台式电脑', name_en: 'desktop computer', keywords: ['computer', 'pc', '电脑'] },
      { char: '🖨️', name_zh: '打印机', name_en: 'printer', keywords: ['print', 'office'] },
      { char: '⌨️', name_zh: '键盘', name_en: 'keyboard', keywords: ['computer', 'type'] },
      { char: '🖱️', name_zh: '鼠标', name_en: 'computer mouse', keywords: ['computer', 'click'] },
      { char: '🖲️', name_zh: '轨迹球', name_en: 'trackball', keywords: ['computer', 'mouse'] },
      { char: '📱', name_zh: '手机', name_en: 'mobile phone', keywords: ['smartphone', 'iphone', '电话'] },
      { char: '📲', name_zh: '带有箭头的手机', name_en: 'mobile phone with arrow', keywords: ['call', 'receive'] },
      { char: '☎️', name_zh: '电话', name_en: 'telephone', keywords: ['call'] },
      { char: '📞', name_zh: '电话听筒', name_en: 'telephone receiver', keywords: ['call'] },
      { char: '📟', name_zh: '寻呼机', name_en: 'pager', keywords: ['call', 'retro'] },
      { char: '📠', name_zh: '传真机', name_en: 'fax machine', keywords: ['office'] },
      { char: '📺', name_zh: '电视', name_en: 'television', keywords: ['tv', 'watch'] },
      { char: '📻', name_zh: '收音机', name_en: 'radio', keywords: ['listen', 'music'] },
      { char: '🎙️', name_zh: '录音室麦克风', name_en: 'studio microphone', keywords: ['sing', 'record'] },
      { char: '🎚️', name_zh: '滑块', name_en: 'level slider', keywords: ['music', 'audio'] },
      { char: '🎛️', name_zh: '控制旋钮', name_en: 'control knobs', keywords: ['music', 'audio'] },
      { char: '🧭', name_zh: '指南针', name_en: 'compass', keywords: ['direction', 'navigation'] },
      { char: '⏱️', name_zh: '秒表', name_en: 'stopwatch', keywords: ['time'] },
      { char: '⏲️', name_zh: '定时器', name_en: 'timer clock', keywords: ['time'] },
      { char: '⏰', name_zh: '闹钟', name_en: 'alarm clock', keywords: ['time', 'wake'] },
      { char: '🕰️', name_zh: '座钟', name_en: 'mantelpiece clock', keywords: ['time'] },
      { char: '⏳', name_zh: '沙漏', name_en: 'hourglass done', keywords: ['time'] },
      { char: '⌛', name_zh: '流沙漏', name_en: 'hourglass not done', keywords: ['time'] },
      { char: '📡', name_zh: '卫星天线', name_en: 'satellite antenna', keywords: ['dish'] },
      { char: '🔋', name_zh: '电池', name_en: 'battery', keywords: ['power'] },
      { char: '🔌', name_zh: '电源插头', name_en: 'electric plug', keywords: ['power'] },
      { char: '💡', name_zh: '灯泡', name_en: 'light bulb', keywords: ['idea', '点子', '灵感'] },
      { char: '🔦', name_zh: '手电筒', name_en: 'flashlight', keywords: ['light', 'camp'] },
      { char: '🕯️', name_zh: '蜡烛', name_en: 'candle', keywords: ['light', 'fire'] },
      { char: '🧯', name_zh: '灭火器', name_en: 'fire extinguisher', keywords: ['fire', 'safety'] },
      { char: '🗑️', name_zh: '废纸篓', name_en: 'wastebasket', keywords: ['trash', 'garbage'] },
      { char: '🛢️', name_zh: '油桶', name_en: 'oil drum', keywords: ['oil', 'barrel'] },
      { char: '💸', name_zh: '长翅膀的钱', name_en: 'money with wings', keywords: ['cash', 'fly'] },
      { char: '💵', name_zh: '美元', name_en: 'dollar banknote', keywords: ['cash', 'money'] },
      { char: '💴', name_zh: '日元', name_en: 'yen banknote', keywords: ['cash', 'money'] },
      { char: '💶', name_zh: '欧元', name_en: 'euro banknote', keywords: ['cash', 'money'] },
      { char: '💷', name_zh: '英镑', name_en: 'pound banknote', keywords: ['cash', 'money'] },
      { char: '💰', name_zh: '钱袋', name_en: 'money bag', keywords: ['cash', 'rich', '钱', '财富'] },
      { char: '💳', name_zh: '信用卡', name_en: 'credit card', keywords: ['money', 'pay'] },
      { char: '💎', name_zh: '宝石', name_en: 'gem stone', keywords: ['diamond', 'jewelry'] },
      { char: '⚖️', name_zh: '天平', name_en: 'balance scale', keywords: ['justice', 'law'] },
      { char: '🧰', name_zh: '工具箱', name_en: 'toolbox', keywords: ['tools', 'fix'] },
      { char: '🔧', name_zh: '扳手', name_en: 'wrench', keywords: ['tools', 'fix'] },
      { char: '🔨', name_zh: '锤子', name_en: 'hammer', keywords: ['tools', 'fix'] },
      { char: '🛠️', name_zh: '锤子和扳手', name_en: 'hammer and wrench', keywords: ['tools', 'fix', '工具', '修理'] },
      { char: '⛏️', name_zh: '镐', name_en: 'pick', keywords: ['tools', 'mine'] },
      { char: '🔩', name_zh: '螺母和螺栓', name_en: 'nut and bolt', keywords: ['tools', 'fix'] },
      { char: '⚙️', name_zh: '齿轮', name_en: 'gear', keywords: ['settings', '设置', '配置'] },
      { char: '🧱', name_zh: '砖块', name_en: 'brick', keywords: ['build', 'wall'] },
      { char: '⛓️', name_zh: '链条', name_en: 'chains', keywords: ['link'] },
      { char: '🧲', name_zh: '磁铁', name_en: 'magnet', keywords: ['attract'] },
      { char: '🔫', name_zh: '水枪', name_en: 'water pistol', keywords: ['gun', 'weapon'] },
      { char: '💣', name_zh: '炸弹', name_en: 'bomb', keywords: ['boom', 'explode'] },
      { char: '🧨', name_zh: '鞭炮', name_en: 'firecracker', keywords: ['explode', 'party'] },
      { char: '🪓', name_zh: '斧头', name_en: 'axe', keywords: ['chop', 'wood'] },
      { char: '🔪', name_zh: '菜刀', name_en: 'kitchen knife', keywords: ['cut', 'cook'] },
      { char: '🗡️', name_zh: '匕首', name_en: 'dagger', keywords: ['weapon', 'sword'] },
      { char: '⚔️', name_zh: '交叉的剑', name_en: 'crossed swords', keywords: ['weapon', 'battle'] },
      { char: '🛡️', name_zh: '盾牌', name_en: 'shield', keywords: ['protect', 'defense'] },
      { char: '🚬', name_zh: '吸烟', name_en: 'cigarette', keywords: ['smoke'] },
      { char: '⚰️', name_zh: '棺材', name_en: 'coffin', keywords: ['dead', 'vampire'] },
      { char: '⚱️', name_zh: '骨灰盒', name_en: 'funeral urn', keywords: ['dead'] },
      { char: '🏺', name_zh: '双耳瓶', name_en: 'amphora', keywords: ['vase', 'history'] },
      { char: '🔮', name_zh: '水晶球', name_en: 'crystal ball', keywords: ['magic', 'fortune'] },
      { char: '📿', name_zh: '念珠', name_en: 'prayer beads', keywords: ['religion', 'pray'] },
      { char: '🧿', name_zh: '邪眼护身符', name_en: 'nazar amulet', keywords: ['evil eye', 'protect'] },
      { char: '💈', name_zh: '理发店标志', name_en: 'barber pole', keywords: ['haircut'] },
      { char: '⚗️', name_zh: '蒸馏器', name_en: 'alembic', keywords: ['chemistry', 'science'] },
      { char: '🔭', name_zh: '望远镜', name_en: 'telescope', keywords: ['stars', 'space'] },
      { char: '🔬', name_zh: '显微镜', name_en: 'microscope', keywords: ['science', 'lab'] },
      { char: '🕳️', name_zh: '孔', name_en: 'hole', keywords: ['pit'] },
      { char: '💊', name_zh: '药丸', name_en: 'pill', keywords: ['medicine', 'doctor'] },
      { char: '💉', name_zh: '注射器', name_en: 'syringe', keywords: ['medicine', 'doctor'] },
      { char: '🩸', name_zh: '血滴', name_en: 'drop of blood', keywords: ['blood', 'donate'] },
      { char: '🧬', name_zh: 'DNA', name_en: 'dna', keywords: ['science', 'genetics'] },
      { char: '🦠', name_zh: '微生物', name_en: 'microbe', keywords: ['virus', 'germ'] },
      { char: '🧫', name_zh: '培养皿', name_en: 'petri dish', keywords: ['science', 'lab'] },
      { char: '🧪', name_zh: '试管', name_en: 'test tube', keywords: ['science', 'lab'] },
      { char: '🌡️', name_zh: '温度计', name_en: 'thermometer', keywords: ['temperature', 'weather'] },
      { char: '🧹', name_zh: '扫帚', name_en: 'broom', keywords: ['clean', 'witch'] },
      { char: '🧺', name_zh: '篮子', name_en: 'basket', keywords: ['laundry', 'picnic'] },
      { char: '🧻', name_zh: '卷纸', name_en: 'roll of paper', keywords: ['toilet paper'] },
      { char: '🚽', name_zh: '马桶', name_en: 'toilet', keywords: ['bathroom'] },
      { char: '🚰', name_zh: '水龙头', name_en: 'potable water', keywords: ['tap', 'sink'] },
      { char: '🚿', name_zh: '淋浴', name_en: 'shower', keywords: ['bath', 'water'] },
      { char: '🛁', name_zh: '浴缸', name_en: 'bathtub', keywords: ['bath', 'water'] },
      { char: '🛀', name_zh: '带人的浴缸', name_en: 'person taking bath', keywords: ['bath'] },
      { char: '🧼', name_zh: '肥皂', name_en: 'soap', keywords: ['clean', 'wash'] },
      { char: '🧽', name_zh: '海绵', name_en: 'sponge', keywords: ['clean', 'wash'] },
      { char: '🧴', name_zh: '乳液瓶', name_en: 'lotion bottle', keywords: ['lotion', 'sunscreen'] },
      { char: '🔑', name_zh: '钥匙', name_en: 'key', keywords: ['password', 'security', '密码', '安全'] },
      { char: '🗝️', name_zh: '老式钥匙', name_en: 'old key', keywords: ['password', 'security'] },
      { char: '🚪', name_zh: '门', name_en: 'door', keywords: ['house', 'entry'] },
      { char: '🪑', name_zh: '椅子', name_en: 'chair', keywords: ['furniture', 'sit'] },
      { char: '🛋️', name_zh: '沙发和灯', name_en: 'couch and lamp', keywords: ['furniture', 'living room'] },
      { char: '🛏️', name_zh: '床', name_en: 'bed', keywords: ['furniture', 'sleep'] },
      { char: '🧸', name_zh: '泰迪熊', name_en: 'teddy bear', keywords: ['toy', 'plush'] },
      { char: '🖼️', name_zh: '带框的画', name_en: 'framed picture', keywords: ['art', 'photo'] },
      { char: '🛍️', name_zh: '购物袋', name_en: 'shopping bags', keywords: ['buy', 'shop'] },
      { char: '🛒', name_zh: '购物车', name_en: 'shopping cart', keywords: ['buy', 'shop'] },
      { char: '🎁', name_zh: '礼物', name_en: 'wrapped gift', keywords: ['present', 'surprise', '惊喜'] },
      { char: '🎈', name_zh: '气球', name_en: 'balloon', keywords: ['party', 'celebration'] },
      { char: '🎏', name_zh: '鲤鱼旗', name_en: 'carp streamer', keywords: ['japan', 'party'] },
      { char: '🎀', name_zh: '蝴蝶结', name_en: 'ribbon', keywords: ['pink', 'girl'] },
      { char: '🎊', name_zh: '五彩纸屑', name_en: 'confetti ball', keywords: ['party', 'celebration'] },
      { char: '🎉', name_zh: '拉炮', name_en: 'party popper', keywords: ['party', 'celebration'] },
      { char: '🎎', name_zh: '日本女儿节人偶', name_en: 'japanese dolls', keywords: ['japan', 'party'] },
      { char: '🏮', name_zh: '红灯笼', name_en: 'red paper lantern', keywords: ['japan', 'light'] },
      { char: '🎐', name_zh: '风铃', name_en: 'wind chime', keywords: ['japan', 'wind'] },
      { char: '🧧', name_zh: '红包', name_en: 'red envelope', keywords: ['money', 'luck'] },
      { char: '✉️', name_zh: '信封', name_en: 'envelope', keywords: ['mail', 'letter'] },
      { char: '📩', name_zh: '带有箭头的信封', name_en: 'envelope with arrow', keywords: ['mail', 'receive'] },
      { char: '📨', name_zh: '收到的邮件', name_en: 'incoming envelope', keywords: ['mail', 'receive'] },
      { char: '📧', name_zh: '电子邮件', name_en: 'e-mail', keywords: ['mail', 'email'] },
      { char: '💌', name_zh: '情书', name_en: 'love letter', keywords: ['mail', 'love'] },
      { char: '📥', name_zh: '收件箱', name_en: 'inbox tray', keywords: ['mail', 'receive'] },
      { char: '📤', name_zh: '发件箱', name_en: 'outbox tray', keywords: ['mail', 'send'] },
      { char: '📦', name_zh: '包裹', name_en: 'package', keywords: ['box', 'delivery', '盒子', '快递'] },
      { char: '🏷️', name_zh: '标签', name_en: 'label', keywords: ['tag'] },
      { char: '📪', name_zh: '关着的邮箱降下旗帜', name_en: 'closed mailbox with lowered flag', keywords: ['mail'] },
      { char: '📫', name_zh: '关着的邮箱升起旗帜', name_en: 'closed mailbox with raised flag', keywords: ['mail'] },
      { char: '📬', name_zh: '开着的邮箱升起旗帜', name_en: 'open mailbox with raised flag', keywords: ['mail'] },
      { char: '📭', name_zh: '开着的邮箱降下旗帜', name_en: 'open mailbox with lowered flag', keywords: ['mail'] },
      { char: '📮', name_zh: '邮筒', name_en: 'postbox', keywords: ['mail'] },
      { char: '📯', name_zh: '邮号', name_en: 'postal horn', keywords: ['mail', 'horn'] },
      { char: '📜', name_zh: '卷轴', name_en: 'scroll', keywords: ['paper', 'history'] },
      { char: '📃', name_zh: '卷起的页面', name_en: 'page with curl', keywords: ['paper', 'document'] },
      { char: '📄', name_zh: '正面朝上的页面', name_en: 'page facing up', keywords: ['paper', 'document'] },
      { char: '📑', name_zh: '书签页', name_en: 'bookmark tabs', keywords: ['paper', 'bookmark'] },
      { char: '🧾', name_zh: '收据', name_en: 'receipt', keywords: ['paper', 'money'] },
      { char: '📊', name_zh: '条形图', name_en: 'bar chart', keywords: ['graph', 'data'] },
      { char: '📈', name_zh: '上升趋势图', name_en: 'chart increasing', keywords: ['graph', 'data', 'up'] },
      { char: '📉', name_zh: '下降趋势图', name_en: 'chart decreasing', keywords: ['graph', 'data', 'down'] },
      { char: '🗒️', name_zh: '螺旋记事本', name_en: 'spiral notepad', keywords: ['paper', 'note'] },
      { char: '🗓️', name_zh: '螺旋日历', name_en: 'spiral calendar', keywords: ['date', 'calendar'] },
      { char: '📆', name_zh: '撕页日历', name_en: 'tear-off calendar', keywords: ['date', 'calendar'] },
      { char: '📅', name_zh: '日历', name_en: 'calendar', keywords: ['date', 'calendar'] },
      { char: '📇', name_zh: '卡片索引', name_en: 'card index', keywords: ['business', 'contact'] },
      { char: '🗃️', name_zh: '卡片索引盒', name_en: 'card index dividers', keywords: ['business', 'contact'] },
      { char: '🗳️', name_zh: '带选票的投票箱', name_en: 'ballot box with ballot', keywords: ['vote', 'election'] },
      { char: '🗄️', name_zh: '文件柜', name_en: 'file cabinet', keywords: ['office', 'file'] },
      { char: '📋', name_zh: '剪贴板', name_en: 'clipboard', keywords: ['office', 'file'] },
      { char: '📁', name_zh: '文件夹', name_en: 'file folder', keywords: ['office', 'file'] },
      { char: '📂', name_zh: '打开的文件夹', name_en: 'open file folder', keywords: ['office', 'file'] },
      { char: '🗂️', name_zh: '卡片索引分隔', name_en: 'card index dividers', keywords: ['office', 'file'] },
      { char: '🗞️', name_zh: '卷起的报纸', name_en: 'rolled-up newspaper', keywords: ['news', 'paper'] },
      { char: '📰', name_zh: '报纸', name_en: 'newspaper', keywords: ['news', 'paper'] },
      { char: '📓', name_zh: '笔记本', name_en: 'notebook', keywords: ['book', 'write'] },
      { char: '📔', name_zh: '带装饰封面的笔记本', name_en: 'notebook with decorative cover', keywords: ['book', 'write'] },
      { char: '📒', name_zh: '账本', name_en: 'ledger', keywords: ['book', 'write'] },
      { char: '📕', name_zh: '闭合的书', name_en: 'closed book', keywords: ['book', 'read'] },
      { char: '📗', name_zh: '绿皮书', name_en: 'green book', keywords: ['book', 'read'] },
      { char: '📘', name_zh: '蓝皮书', name_en: 'blue book', keywords: ['book', 'read'] },
      { char: '📙', name_zh: '橙皮书', name_en: 'orange book', keywords: ['book', 'read'] },
      { char: '📚', name_zh: '书本', name_en: 'books', keywords: ['book', 'read'] },
      { char: '📖', name_zh: '打开的书', name_en: 'open book', keywords: ['read', 'study', '阅读', '学习'] },
      { char: '🔖', name_zh: '书签', name_en: 'bookmark', keywords: ['book', 'mark'] },
      { char: '🧷', name_zh: '安全别针', name_en: 'safety pin', keywords: ['pin', 'fasten'] },
      { char: '🔗', name_zh: '链接', name_en: 'link', keywords: ['chain', 'url'] },
      { char: '📎', name_zh: '回形针', name_en: 'paperclip', keywords: ['attach', 'file'] },
      { char: '🖇️', name_zh: '连接的回形针', name_en: 'linked paperclips', keywords: ['attach', 'file'] },
      { char: '📐', name_zh: '三角尺', name_en: 'triangular ruler', keywords: ['math', 'measure'] },
      { char: '📏', name_zh: '直尺', name_en: 'straight ruler', keywords: ['math', 'measure'] },
      { char: '🧮', name_zh: '算盘', name_en: 'abacus', keywords: ['math', 'calculate'] },
      { char: '📌', name_zh: '图钉', name_en: 'pushpin', keywords: ['pin', 'attach'] },
      { char: '📍', name_zh: '圆头图钉', name_en: 'round pushpin', keywords: ['pin', 'location'] },
      { char: '✂️', name_zh: '剪刀', name_en: 'scissors', keywords: ['cut', 'tool'] },
      { char: '🖊️', name_zh: '钢笔', name_en: 'pen', keywords: ['write', 'tool'] },
      { char: '🖋️', name_zh: '墨水笔', name_en: 'fountain pen', keywords: ['write', 'tool'] },
      { char: '✒️', name_zh: '黑色笔尖', name_en: 'black nib', keywords: ['write', 'tool'] },
      { char: '🖌️', name_zh: '画笔', name_en: 'paintbrush', keywords: ['paint', 'art'] },
      { char: '🖍️', name_zh: '蜡笔', name_en: 'crayon', keywords: ['draw', 'art'] },
      { char: '✏️', name_zh: '铅笔', name_en: 'pencil', keywords: ['write', 'edit', '写作', '编辑'] },
      { char: '🔍', name_zh: '向左的放大镜', name_en: 'magnifying glass tilted left', keywords: ['search', 'find'] },
      { char: '🔎', name_zh: '向右的放大镜', name_en: 'magnifying glass tilted right', keywords: ['search', 'find'] },
      { char: '🔏', name_zh: '带钢笔的锁', name_en: 'locked with pen', keywords: ['security', 'privacy'] },
      { char: '🔐', name_zh: '带钥匙的锁', name_en: 'locked with key', keywords: ['security', 'privacy'] },
      { char: '🔒', name_zh: '锁', name_en: 'locked', keywords: ['private', 'secure', '私密', '锁定'] },
      { char: '🔓', name_zh: '打开的锁', name_en: 'unlocked', keywords: ['security', 'privacy'] }
    ]
  },
  {
    name: '符号',
    groupIcon: 'Heart',
    emojis: [
      { char: '❤️', name_zh: '红心', name_en: 'red heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '🧡', name_zh: '橙心', name_en: 'orange heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💛', name_zh: '黄心', name_en: 'yellow heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💚', name_zh: '绿心', name_en: 'green heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💙', name_zh: '蓝心', name_en: 'blue heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💜', name_zh: '紫心', name_en: 'purple heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '🖤', name_zh: '黑心', name_en: 'black heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '🤍', name_zh: '白心', name_en: 'white heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '🤎', name_zh: '棕心', name_en: 'brown heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💔', name_zh: '心碎', name_en: 'broken heart', keywords: ['sad', '伤心'] },
      { char: '❣️', name_zh: '心形感叹号', name_en: 'heavy heart exclamation mark ornament', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💕', name_zh: '两颗心', name_en: 'two hearts', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💞', name_zh: '旋转的心', name_en: 'revolving hearts', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💓', name_zh: '跳动的心', name_en: 'beating heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💗', name_zh: '成长的心', name_en: 'growing heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💖', name_zh: '闪亮的心', name_en: 'sparkling heart', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💘', name_zh: '射中的心', name_en: 'heart with arrow', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💝', name_zh: '带缎带的心', name_en: 'heart with ribbon', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '💟', name_zh: '心形装饰', name_en: 'heart decoration', keywords: ['love', 'like', '爱', '喜欢'] },
      { char: '☮️', name_zh: '和平符号', name_en: 'peace symbol', keywords: ['peace', 'harmony'] },
      { char: '✝️', name_zh: '拉丁十字架', name_en: 'latin cross', keywords: ['religion', 'christianity'] },
      { char: '☪️', name_zh: '星月', name_en: 'star and crescent', keywords: ['religion', 'islam'] },
      { char: '🕉️', name_zh: '唵', name_en: 'om', keywords: ['religion', 'hinduism'] },
      { char: '☸️', name_zh: '法轮', name_en: 'wheel of dharma', keywords: ['religion', 'buddhism'] },
      { char: '✡️', name_zh: '大卫之星', name_en: 'star of david', keywords: ['religion', 'judaism'] },
      { char: '🔯', name_zh: '六角星', name_en: 'six-pointed star', keywords: ['religion', 'judaism'] },
      { char: '🕎', name_zh: '七灯台', name_en: 'menorah', keywords: ['religion', 'judaism'] },
      { char: '☯️', name_zh: '阴阳', name_en: 'yin yang', keywords: ['religion', 'taoism'] },
      { char: '☦️', name_zh: '正统十字架', name_en: 'orthodox cross', keywords: ['religion', 'christianity'] },
      { char: '🛐', name_zh: '宗教场所', name_en: 'place of worship', keywords: ['religion', 'pray'] },
      { char: '⛎', name_zh: '蛇夫座', name_en: 'ophiuchus', keywords: ['zodiac', 'astrology'] },
      { char: '♈', name_zh: '白羊座', name_en: 'aries', keywords: ['zodiac', 'astrology'] },
      { char: '♉', name_zh: '金牛座', name_en: 'taurus', keywords: ['zodiac', 'astrology'] },
      { char: '♊', name_zh: '双子座', name_en: 'gemini', keywords: ['zodiac', 'astrology'] },
      { char: '♋', name_zh: '巨蟹座', name_en: 'cancer', keywords: ['zodiac', 'astrology'] },
      { char: '♌', name_zh: '狮子座', name_en: 'leo', keywords: ['zodiac', 'astrology'] },
      { char: '♍', name_zh: '处女座', name_en: 'virgo', keywords: ['zodiac', 'astrology'] },
      { char: '♎', name_zh: '天秤座', name_en: 'libra', keywords: ['zodiac', 'astrology'] },
      { char: '♏', name_zh: '天蝎座', name_en: 'scorpio', keywords: ['zodiac', 'astrology'] },
      { char: '♐', name_zh: '射手座', name_en: 'sagittarius', keywords: ['zodiac', 'astrology'] },
      { char: '♑', name_zh: '摩羯座', name_en: 'capricorn', keywords: ['zodiac', 'astrology'] },
      { char: '♒', name_zh: '水瓶座', name_en: 'aquarius', keywords: ['zodiac', 'astrology'] },
      { char: '♓', name_zh: '双鱼座', name_en: 'pisces', keywords: ['zodiac', 'astrology'] },
      { char: '🆔', name_zh: 'ID 按钮', name_en: 'ID button', keywords: ['id', 'identity'] },
      { char: '⚛️', name_zh: '原子的符号', name_en: 'atom symbol', keywords: ['science', 'physics'] },
      { char: '🈳', name_zh: '空', name_en: 'Japanese “vacancy” button', keywords: ['empty'] },
      { char: '🈹', name_zh: '割', name_en: 'Japanese “discount” button', keywords: ['discount'] },
      { char: '☢️', name_zh: '放射性', name_en: 'radioactive', keywords: ['danger', 'warning'] },
      { char: '☣️', name_zh: '生物危害', name_en: 'biohazard', keywords: ['danger', 'warning'] },
      { char: '📴', name_zh: '手机关机', name_en: 'mobile phone off', keywords: ['off'] },
      { char: '📳', name_zh: '手机震动', name_en: 'vibration mode', keywords: ['vibrate'] },
      { char: '🈶', name_zh: '有', name_en: 'Japanese “not free of charge” button', keywords: ['charge'] },
      { char: '🈚', name_zh: '无', name_en: 'Japanese “free of charge” button', keywords: ['free'] },
      { char: '🈸', name_zh: '申', name_en: 'Japanese “application” button', keywords: ['apply'] },
      { char: '🈺', name_zh: '营', name_en: 'Japanese “open for business” button', keywords: ['open'] },
      { char: '🈷️', name_zh: '月', name_en: 'Japanese “monthly amount” button', keywords: ['month'] },
      { char: '🆚', name_zh: '对决', name_en: 'VS button', keywords: ['versus'] },
      { char: '🉑', name_zh: '可', name_en: 'Japanese “acceptable” button', keywords: ['accept'] },
      { char: '🚰', name_zh: '水', name_en: 'Japanese “water” button', keywords: ['water'] },
      { char: '🉐', name_zh: '得', name_en: 'Japanese “bargain” button', keywords: ['bargain'] },
      { char: '㊙️', name_zh: '秘', name_en: 'Japanese “secret” button', keywords: ['secret'] },
      { char: '㊗️', name_zh: '祝', name_en: 'Japanese “congratulations” button', keywords: ['congrats'] },
      { char: '🈴', name_zh: '合', name_en: 'Japanese “passing grade” button', keywords: ['pass'] },
      { char: '🈵', name_zh: '满', name_en: 'Japanese “no vacancy” button', keywords: ['full'] },
      { char: '💯', name_zh: '一百分', name_en: 'hundred points', keywords: ['perfect', 'score', '满分', '完美'] },
      { char: '✅', name_zh: '对号', name_en: 'check mark button', keywords: ['done', 'ok', '完成', '确认'] },
      { char: '❌', name_zh: '错号', name_en: 'cross mark', keywords: ['cancel', 'no', '取消', '错误'] },
      { char: '❗', name_zh: '感叹号', name_en: 'exclamation mark', keywords: ['warning', 'attention', '警告', '注意'] },
      { char: '❓', name_zh: '问号', name_en: 'question mark', keywords: ['help', 'what', '疑问', '帮助'] },
      { char: '💤', name_zh: '打呼噜', name_en: 'zzz', keywords: ['sleep', '睡觉'] },
      { char: '💬', name_zh: '气泡', name_en: 'speech balloon', keywords: ['chat', 'message', '聊天', '消息'] },
      { char: '🔔', name_zh: '铃铛', name_en: 'bell', keywords: ['notification', '通知', '提醒'] },
      { char: '🔕', name_zh: '静音铃铛', name_en: 'bell with slash', keywords: ['mute', 'quiet'] },
      { char: '🎵', name_zh: '音符', name_en: 'musical note', keywords: ['music', 'song'] },
      { char: '🎶', name_zh: '多个音符', name_en: 'musical notes', keywords: ['music', 'song'] }
    ]
  },
  {
    name: '旅行与地点',
    groupIcon: 'Map',
    emojis: [
      { char: '🚗', name_zh: '汽车', name_en: 'automobile', keywords: ['car', 'drive', '车', '交通'] },
      { char: '🚕', name_zh: '出租车', name_en: 'taxi', keywords: ['cab', '打车'] },
      { char: '🚙', name_zh: '越野车', name_en: 'sport utility vehicle', keywords: ['suv', '车'] },
      { char: '🚌', name_zh: '公交车', name_en: 'bus', keywords: ['transport', '巴士'] },
      { char: '🚎', name_zh: '无轨电车', name_en: 'trolleybus', keywords: ['transport'] },
      { char: '🏎️', name_zh: '赛车', name_en: 'racing car', keywords: ['fast', 'speed', 'f1'] },
      { char: '🚓', name_zh: '警车', name_en: 'police car', keywords: ['police', 'cop', '警察'] },
      { char: '🚑', name_zh: '救护车', name_en: 'ambulance', keywords: ['hospital', 'help', '急救'] },
      { char: '🚒', name_zh: '消防车', name_en: 'fire engine', keywords: ['fire', '消防'] },
      { char: '🚐', name_zh: '小巴', name_en: 'minibus', keywords: ['van'] },
      { char: '🛻', name_zh: '皮卡车', name_en: 'pickup truck', keywords: ['truck'] },
      { char: '🚚', name_zh: '货车', name_en: 'delivery truck', keywords: ['truck', 'delivery', '送货'] },
      { char: '🚜', name_zh: '拖拉机', name_en: 'tractor', keywords: ['farm'] },
      { char: '🛴', name_zh: '滑板车', name_en: 'kick scooter', keywords: ['ride'] },
      { char: '🚲', name_zh: '自行车', name_en: 'bicycle', keywords: ['bike', 'ride', '单车'] },
      { char: '🛵', name_zh: '小型摩托车', name_en: 'motor scooter', keywords: ['ride'] },
      { char: '🏍️', name_zh: '摩托车', name_en: 'motorcycle', keywords: ['ride', 'bike'] },
      { char: '🚨', name_zh: '警车灯', name_en: 'police car light', keywords: ['police', 'warning', '警告'] },
      { char: '✈️', name_zh: '飞机', name_en: 'airplane', keywords: ['flight', 'travel', '飞行', '旅游'] },
      { char: '🛫', name_zh: '飞机起飞', name_en: 'airplane departure', keywords: ['flight', 'travel', '出发'] },
      { char: '🛬', name_zh: '飞机降落', name_en: 'airplane arrival', keywords: ['flight', 'travel', '到达'] },
      { char: '🚀', name_zh: '火箭', name_en: 'rocket', keywords: ['space', 'launch', '起飞', '快速'] },
      { char: '🛸', name_zh: '飞碟', name_en: 'flying saucer', keywords: ['ufo', 'alien', '外星人'] },
      { char: '🚁', name_zh: '直升机', name_en: 'helicopter', keywords: ['flight'] },
      { char: '🛶', name_zh: '独木舟', name_en: 'canoe', keywords: ['boat', 'water'] },
      { char: '⛵', name_zh: '帆船', name_en: 'sailboat', keywords: ['boat', 'sea', '海'] },
      { char: '🚤', name_zh: '快艇', name_en: 'speedboat', keywords: ['boat', 'water'] },
      { char: '🛳️', name_zh: '客轮', name_en: 'passenger ship', keywords: ['boat', 'cruise'] },
      { char: '⛴️', name_zh: '渡轮', name_en: 'ferry', keywords: ['boat', 'water'] },
      { char: '🚢', name_zh: '船', name_en: 'ship', keywords: ['boat', 'sea'] },
      { char: '⚓', name_zh: '锚', name_en: 'anchor', keywords: ['sea', 'boat'] },
      { char: '⛽', name_zh: '加油站', name_en: 'fuel pump', keywords: ['gas', 'station'] },
      { char: '🚧', name_zh: '路障', name_en: 'construction', keywords: ['warning', '施工'] },
      { char: '🚦', name_zh: '纵向红绿灯', name_en: 'vertical traffic light', keywords: ['traffic', 'stop'] },
      { char: '🚥', name_zh: '横向红绿灯', name_en: 'horizontal traffic light', keywords: ['traffic', 'stop'] },
      { char: '🗺️', name_zh: '世界地图', name_en: 'world map', keywords: ['map', 'travel', '地图'] },
      { char: '🗿', name_zh: '复活节岛人像', name_en: 'moai', keywords: ['stone', 'statue', '雕像'] },
      { char: '🗽', name_zh: '自由女神像', name_en: 'Statue of Liberty', keywords: ['new york', 'usa'] },
      { char: '🗼', name_zh: '东京塔', name_en: 'Tokyo tower', keywords: ['japan'] },
      { char: '🏰', name_zh: '城堡', name_en: 'castle', keywords: ['royalty', 'history'] },
      { char: '🏯', name_zh: '日本城堡', name_en: 'Japanese castle', keywords: ['japan', 'history'] },
      { char: '🏟️', name_zh: '体育馆', name_en: 'stadium', keywords: ['sports', 'event'] },
      { char: '🎡', name_zh: '摩天轮', name_en: 'ferris wheel', keywords: ['amusement park'] },
      { char: '🎢', name_zh: '过山车', name_en: 'roller coaster', keywords: ['amusement park'] },
      { char: '🎠', name_zh: '旋转木马', name_en: 'carousel horse', keywords: ['amusement park'] },
      { char: '⛲', name_zh: '喷泉', name_en: 'fountain', keywords: ['water', 'park'] },
      { char: '⛱️', name_zh: '沙滩伞', name_en: 'umbrella on ground', keywords: ['beach', 'summer'] },
      { char: '🏖️', name_zh: '沙滩和遮阳伞', name_en: 'beach with umbrella', keywords: ['beach', 'summer', '海滩'] },
      { char: '🏝️', name_zh: '荒岛', name_en: 'desert island', keywords: ['island', 'beach'] },
      { char: '🏜️', name_zh: '沙漠', name_en: 'desert', keywords: ['sand', 'dry'] },
      { char: '🌋', name_zh: '火山', name_en: 'volcano', keywords: ['mountain', 'lava'] },
      { char: '⛰️', name_zh: '山', name_en: 'mountain', keywords: ['hill', 'nature'] },
      { char: '🏔️', name_zh: '雪山', name_en: 'snow-capped mountain', keywords: ['mountain', 'snow'] },
      { char: '🗻', name_zh: '富士山', name_en: 'mount fuji', keywords: ['japan', 'mountain'] },
      { char: '🏕️', name_zh: '露营', name_en: 'camping', keywords: ['tent', 'outdoors'] },
      { char: '⛺', name_zh: '帐篷', name_en: 'tent', keywords: ['camping', 'outdoors'] },
      { char: '🏠', name_zh: '房子', name_en: 'house', keywords: ['home', 'building', '家'] },
      { char: '🏡', name_zh: '带花园的房子', name_en: 'house with garden', keywords: ['home', 'house'] },
      { char: '🏢', name_zh: '办公楼', name_en: 'office building', keywords: ['building', 'work', '办公'] },
      { char: '🏣', name_zh: '日本邮局', name_en: 'Japanese post office', keywords: ['building'] },
      { char: '🏤', name_zh: '邮局', name_en: 'post office', keywords: ['building'] },
      { char: '🏥', name_zh: '医院', name_en: 'hospital', keywords: ['building', 'medical'] },
      { char: '🏦', name_zh: '银行', name_en: 'bank', keywords: ['building', 'money'] },
      { char: '🏨', name_zh: '酒店', name_en: 'hotel', keywords: ['building', 'travel'] },
      { char: '🏪', name_zh: '便利店', name_en: 'convenience store', keywords: ['building', 'shop'] },
      { char: '🏫', name_zh: '学校', name_en: 'school', keywords: ['building', 'education'] },
      { char: '🏬', name_zh: '百货大楼', name_en: 'department store', keywords: ['building', 'shop'] },
      { char: '🏭', name_zh: '工厂', name_en: 'factory', keywords: ['building', 'industry'] }
    ]
  },
  {
    name: '旗帜',
    groupIcon: 'Flag',
    emojis: [
      { char: '🇨🇳', name_zh: '中国', name_en: 'China', keywords: ['china', 'flag', '国旗'] },
      { char: '🇺🇸', name_zh: '美国', name_en: 'United States', keywords: ['usa', 'flag', '国旗'] },
      { char: '🇬🇧', name_zh: '英国', name_en: 'United Kingdom', keywords: ['uk', 'flag', '国旗'] },
      { char: '🇯🇵', name_zh: '日本', name_en: 'Japan', keywords: ['japan', 'flag', '国旗'] },
      { char: '🇰🇷', name_zh: '韩国', name_en: 'South Korea', keywords: ['korea', 'flag', '国旗'] },
      { char: '🇩🇪', name_zh: '德国', name_en: 'Germany', keywords: ['germany', 'flag', '国旗'] },
      { char: '🇫🇷', name_zh: '法国', name_en: 'France', keywords: ['france', 'flag', '国旗'] },
      { char: '🇮🇹', name_zh: '意大利', name_en: 'Italy', keywords: ['italy', 'flag', '国旗'] },
      { char: '🇷🇺', name_zh: '俄罗斯', name_en: 'Russia', keywords: ['russia', 'flag', '国旗'] },
      { char: '🇨🇦', name_zh: '加拿大', name_en: 'Canada', keywords: ['canada', 'flag', '国旗'] },
      { char: '🇦🇺', name_zh: '澳大利亚', name_en: 'Australia', keywords: ['australia', 'flag', '国旗'] },
      { char: '🇧🇷', name_zh: '巴西', name_en: 'Brazil', keywords: ['brazil', 'flag', '国旗'] },
      { char: '🇮🇳', name_zh: '印度', name_en: 'India', keywords: ['india', 'flag', '国旗'] },
      { char: '🇪🇸', name_zh: '西班牙', name_en: 'Spain', keywords: ['spain', 'flag', '国旗'] },
      { char: '🇲🇽', name_zh: '墨西哥', name_en: 'Mexico', keywords: ['mexico', 'flag', '国旗'] },
      { char: '🇦🇷', name_zh: '阿根廷', name_en: 'Argentina', keywords: ['argentina', 'flag', '国旗'] },
      { char: '🇿🇦', name_zh: '南非', name_en: 'South Africa', keywords: ['south africa', 'flag', '国旗'] },
      { char: '🇪🇬', name_zh: '埃及', name_en: 'Egypt', keywords: ['egypt', 'flag', '国旗'] },
      { char: '🇸🇦', name_zh: '沙特阿拉伯', name_en: 'Saudi Arabia', keywords: ['saudi arabia', 'flag', '国旗'] },
      { char: '🇦🇪', name_zh: '阿联酋', name_en: 'United Arab Emirates', keywords: ['uae', 'flag', '国旗'] },
      { char: '🇹🇷', name_zh: '土耳其', name_en: 'Turkey', keywords: ['turkey', 'flag', '国旗'] },
      { char: '🇮🇱', name_zh: '以色列', name_en: 'Israel', keywords: ['israel', 'flag', '国旗'] },
      { char: '🇵🇰', name_zh: '巴基斯坦', name_en: 'Pakistan', keywords: ['pakistan', 'flag', '国旗'] },
      { char: '🇮🇩', name_zh: '印度尼西亚', name_en: 'Indonesia', keywords: ['indonesia', 'flag', '国旗'] },
      { char: '🇲🇾', name_zh: '马来西亚', name_en: 'Malaysia', keywords: ['malaysia', 'flag', '国旗'] },
      { char: '🇵🇭', name_zh: '菲律宾', name_en: 'Philippines', keywords: ['philippines', 'flag', '国旗'] },
      { char: '🇹🇭', name_zh: '泰国', name_en: 'Thailand', keywords: ['thailand', 'flag', '国旗'] },
      { char: '🇻🇳', name_zh: '越南', name_en: 'Vietnam', keywords: ['vietnam', 'flag', '国旗'] },
      { char: '🇸🇬', name_zh: '新加坡', name_en: 'Singapore', keywords: ['singapore', 'flag', '国旗'] },
      { char: '🇳🇿', name_zh: '新西兰', name_en: 'New Zealand', keywords: ['new zealand', 'flag', '国旗'] },
      { char: '🇨🇭', name_zh: '瑞士', name_en: 'Switzerland', keywords: ['switzerland', 'flag', '国旗'] },
      { char: '🇸🇪', name_zh: '瑞典', name_en: 'Sweden', keywords: ['sweden', 'flag', '国旗'] },
      { char: '🇳🇴', name_zh: '挪威', name_en: 'Norway', keywords: ['norway', 'flag', '国旗'] },
      { char: '🇩🇰', name_zh: '丹麦', name_en: 'Denmark', keywords: ['denmark', 'flag', '国旗'] },
      { char: '🇫🇮', name_zh: '芬兰', name_en: 'Finland', keywords: ['finland', 'flag', '国旗'] },
      { char: '🇳🇱', name_zh: '荷兰', name_en: 'Netherlands', keywords: ['netherlands', 'flag', '国旗'] },
      { char: '🇧🇪', name_zh: '比利时', name_en: 'Belgium', keywords: ['belgium', 'flag', '国旗'] },
      { char: '🇦🇹', name_zh: '奥地利', name_en: 'Austria', keywords: ['austria', 'flag', '国旗'] },
      { char: '🇬🇷', name_zh: '希腊', name_en: 'Greece', keywords: ['greece', 'flag', '国旗'] },
      { char: '🇵🇹', name_zh: '葡萄牙', name_en: 'Portugal', keywords: ['portugal', 'flag', '国旗'] },
      { char: '🇵🇱', name_zh: '波兰', name_en: 'Poland', keywords: ['poland', 'flag', '国旗'] },
      { char: '🇺🇦', name_zh: '乌克兰', name_en: 'Ukraine', keywords: ['ukraine', 'flag', '国旗'] },
      { char: '🇮🇪', name_zh: '爱尔兰', name_en: 'Ireland', keywords: ['ireland', 'flag', '国旗'] },
      { char: '🇪🇺', name_zh: '欧盟', name_en: 'European Union', keywords: ['eu', 'flag', '欧盟', '旗帜'] },
      { char: '🇺🇳', name_zh: '联合国', name_en: 'United Nations', keywords: ['un', 'flag', '联合国', '旗帜'] },
      { char: '🏴‍☠️', name_zh: '海盗旗', name_en: 'pirate flag', keywords: ['pirate', 'jolly roger', '海盗'] },
      { char: '🏁', name_zh: '方格旗', name_en: 'chequered flag', keywords: ['race', 'finish', '终点', '比赛'] },
      { char: '🚩', name_zh: '三角红旗', name_en: 'triangular flag', keywords: ['flag', 'red', '红旗', '标记'] },
      { char: '🏳️', name_zh: '白旗', name_en: 'white flag', keywords: ['flag', 'surrender', '投降'] },
      { char: '🏳️‍🌈', name_zh: '彩虹旗', name_en: 'rainbow flag', keywords: ['pride', 'rainbow', '彩虹'] }
    ]
  }
];
