export interface IconItem {
  id: string; // the name of the Lucide icon component, e.g. "Activity"
  name_zh: string;
  keywords: string[];
}

export interface IconGroup {
  name: string;
  groupIcon: string;
  icons: IconItem[];
}

export const ICON_DATA: IconGroup[] = [
  {
    name: '基础与常用',
    groupIcon: 'Home',
    icons: [
      { id: 'Home', name_zh: '主页', keywords: ['home', 'house', '首页', '房子'] },
      { id: 'Settings', name_zh: '设置', keywords: ['settings', 'gear', '配置', '齿轮'] },
      { id: 'Search', name_zh: '搜索', keywords: ['search', 'find', 'magnifying glass', '查找', '放大镜'] },
      { id: 'User', name_zh: '用户', keywords: ['user', 'person', 'account', '账号', '人'] },
      { id: 'Users', name_zh: '用户群', keywords: ['users', 'team', '团队', '人群'] },
      { id: 'Star', name_zh: '收藏', keywords: ['star', 'favorite', '星星'] },
      { id: 'Heart', name_zh: '喜欢', keywords: ['heart', 'love', '心'] },
      { id: 'Check', name_zh: '确认', keywords: ['check', 'tick', 'done', '完成', '对勾'] },
      { id: 'CheckCircle2', name_zh: '完成', keywords: ['check', 'done', 'success', '圆圈对勾'] },
      { id: 'X', name_zh: '关闭', keywords: ['x', 'close', 'cancel', '取消', '叉号'] },
      { id: 'XCircle', name_zh: '错误', keywords: ['error', 'fail', 'cancel', '错误', '取消'] },
      { id: 'Plus', name_zh: '添加', keywords: ['plus', 'add', 'new', '新增', '加号'] },
      { id: 'PlusCircle', name_zh: '添加', keywords: ['plus', 'add', 'new', '新增圆圈'] },
      { id: 'Trash2', name_zh: '删除', keywords: ['trash', 'delete', 'remove', '垃圾桶', '移除'] },
      { id: 'Edit3', name_zh: '编辑', keywords: ['edit', 'pencil', 'write', '修改', '笔'] },
      { id: 'Copy', name_zh: '复制', keywords: ['copy', 'duplicate', '拷贝'] },
      { id: 'Share2', name_zh: '分享', keywords: ['share', 'send', '发送'] },
      { id: 'MoreHorizontal', name_zh: '更多', keywords: ['more', 'menu', '菜单', '省略号'] },
      { id: 'MoreVertical', name_zh: '更多选项', keywords: ['more', 'menu', '竖省略号'] },
      { id: 'RefreshCw', name_zh: '刷新', keywords: ['refresh', 'reload', 'sync', '同步'] },
      { id: 'History', name_zh: '历史', keywords: ['history', 'recent', 'time', '最近'] },
      { id: 'Bookmark', name_zh: '书签', keywords: ['bookmark', 'save', 'mark', '书签', '保存'] },
      { id: 'Key', name_zh: '钥匙', keywords: ['key', 'password', 'security', '密码', '钥匙'] },
      { id: 'Link', name_zh: '链接', keywords: ['link', 'url', 'chain', '链接'] },
      { id: 'Paperclip', name_zh: '附件', keywords: ['paperclip', 'attachment', 'file', '附件'] },
      { id: 'AlertCircle', name_zh: '警告提示', keywords: ['alert', 'warning', 'error', '警告'] },
      { id: 'AlertTriangle', name_zh: '危险警告', keywords: ['alert', 'triangle', 'danger', '危险'] },
      { id: 'Info', name_zh: '信息', keywords: ['info', 'information', 'about', '信息', '关于'] },
      { id: 'HelpCircle', name_zh: '帮助', keywords: ['help', 'question', 'support', '帮助', '疑问'] },
    ]
  },
  {
    name: '商业与工作',
    groupIcon: 'Briefcase',
    icons: [
      { id: 'Briefcase', name_zh: '公文包', keywords: ['briefcase', 'work', 'business', '工作', '商务'] },
      { id: 'Building2', name_zh: '公司', keywords: ['building', 'office', 'company', '建筑', '大楼'] },
      { id: 'Store', name_zh: '商店', keywords: ['store', 'shop', '店铺'] },
      { id: 'Wallet', name_zh: '钱包', keywords: ['wallet', 'money', 'finance', '钱', '金融'] },
      { id: 'Banknote', name_zh: '纸币', keywords: ['cash', 'money', '现金', '钞票'] },
      { id: 'CreditCard', name_zh: '信用卡', keywords: ['card', 'payment', '支付', '银行卡'] },
      { id: 'PiggyBank', name_zh: '存钱罐', keywords: ['save', 'money', '储蓄'] },
      { id: 'BarChart3', name_zh: '柱状图', keywords: ['chart', 'graph', 'analytics', '数据', '分析'] },
      { id: 'LineChart', name_zh: '折线图', keywords: ['chart', 'graph', 'analytics', '数据', '分析'] },
      { id: 'PieChart', name_zh: '饼图', keywords: ['pie chart', 'analytics', '比例', '数据'] },
      { id: 'TrendingUp', name_zh: '上升趋势', keywords: ['trending', 'up', 'growth', '增长', '上升'] },
      { id: 'TrendingDown', name_zh: '下降趋势', keywords: ['trending', 'down', 'loss', '下降'] },
      { id: 'Target', name_zh: '目标', keywords: ['target', 'goal', 'bullseye', '靶子'] },
      { id: 'Calendar', name_zh: '日历', keywords: ['calendar', 'date', 'schedule', '日期', '日程'] },
      { id: 'CalendarDays', name_zh: '日历(多天)', keywords: ['calendar', 'date', 'schedule', '日期'] },
      { id: 'Clock', name_zh: '时钟', keywords: ['clock', 'time', '时间', '表'] },
      { id: 'Timer', name_zh: '计时器', keywords: ['timer', 'time', '计时'] },
      { id: 'ClipboardList', name_zh: '任务板', keywords: ['clipboard', 'tasks', 'todo', '待办', '清单'] },
      { id: 'Calculator', name_zh: '计算器', keywords: ['math', 'calc', '计算'] },
      { id: 'Activity', name_zh: '活动', keywords: ['activity', 'pulse', 'health', '活动', '数据'] },
      { id: 'BadgePercent', name_zh: '百分比徽章', keywords: ['badge', 'percent', 'discount', '折扣', '百分比'] },
      { id: 'Coins', name_zh: '硬币', keywords: ['coins', 'money', '金币'] },
      { id: 'DollarSign', name_zh: '美元', keywords: ['dollar', 'currency', 'money', '钱'] },
      { id: 'Euro', name_zh: '欧元', keywords: ['euro', 'currency', 'money', '钱'] },
      { id: 'Percent', name_zh: '百分号', keywords: ['percent', 'discount', '百分比'] },
      { id: 'Receipt', name_zh: '收据', keywords: ['receipt', 'bill', 'invoice', '账单', '发票'] },
      { id: 'Building', name_zh: '建筑', keywords: ['building', 'architecture', '建筑'] },
      { id: 'Factory', name_zh: '工厂', keywords: ['factory', 'industry', '工厂', '工业'] },
      { id: 'Landmark', name_zh: '地标', keywords: ['landmark', 'monument', '地标', '建筑'] },
      { id: 'MapPin', name_zh: '定位针', keywords: ['map', 'pin', 'location', '定位', '位置'] },
    ]
  },
  {
    name: '通讯与设备',
    groupIcon: 'Smartphone',
    icons: [
      { id: 'Mail', name_zh: '邮件', keywords: ['mail', 'email', 'message', '邮箱', '信息'] },
      { id: 'Send', name_zh: '发送', keywords: ['send', 'message', 'paper plane', '纸飞机'] },
      { id: 'MessageSquare', name_zh: '消息', keywords: ['message', 'chat', 'comment', '聊天', '评论'] },
      { id: 'MessageCircle', name_zh: '聊天', keywords: ['message', 'chat', 'comment', '聊天气泡'] },
      { id: 'Phone', name_zh: '电话', keywords: ['phone', 'call', '拨号', '手机'] },
      { id: 'PhoneCall', name_zh: '呼叫', keywords: ['phone', 'call', '拨打'] },
      { id: 'Bell', name_zh: '通知', keywords: ['bell', 'notification', 'alert', '铃铛', '提醒'] },
      { id: 'BellRing', name_zh: '响铃', keywords: ['bell', 'notification', 'alert', '震动'] },
      { id: 'Camera', name_zh: '相机', keywords: ['camera', 'photo', '照片', '拍照'] },
      { id: 'Video', name_zh: '视频', keywords: ['video', 'camera', 'movie', '录像', '摄像'] },
      { id: 'Monitor', name_zh: '显示器', keywords: ['monitor', 'screen', 'desktop', '电脑', '屏幕'] },
      { id: 'Smartphone', name_zh: '智能手机', keywords: ['smartphone', 'mobile', 'device', '手机'] },
      { id: 'Laptop', name_zh: '笔记本电脑', keywords: ['laptop', 'computer', 'mac', '电脑'] },
      { id: 'Tablet', name_zh: '平板电脑', keywords: ['tablet', 'ipad', '平板'] },
      { id: 'Headphones', name_zh: '头戴式耳机', keywords: ['headphones', 'listen', '听', '耳麦'] },
      { id: 'Mic', name_zh: '麦克风', keywords: ['microphone', 'record', '录音', '语音'] },
      { id: 'Wifi', name_zh: '无线网', keywords: ['wifi', 'internet', 'connection', '网络', '连接'] },
      { id: 'Bluetooth', name_zh: '蓝牙', keywords: ['bluetooth', 'connection', '连接'] },
      { id: 'BatteryFull', name_zh: '电池满', keywords: ['battery', 'power', '电量'] },
      { id: 'Cast', name_zh: '投屏', keywords: ['cast', 'stream', 'tv', '投屏'] },
      { id: 'Computer', name_zh: '电脑', keywords: ['computer', 'pc', '电脑'] },
      { id: 'Gamepad2', name_zh: '游戏手柄', keywords: ['game', 'play', 'console', '游戏'] },
      { id: 'Keyboard', name_zh: '键盘', keywords: ['keyboard', 'type', '键盘'] },
      { id: 'Mouse', name_zh: '鼠标', keywords: ['mouse', 'click', '鼠标'] },
      { id: 'Printer', name_zh: '打印机', keywords: ['printer', 'document', '打印'] },
      { id: 'Radio', name_zh: '收音机', keywords: ['radio', 'broadcast', '广播'] },
      { id: 'Router', name_zh: '路由器', keywords: ['router', 'wifi', 'network', '网络', '路由'] },
      { id: 'Speaker', name_zh: '扬声器', keywords: ['speaker', 'audio', 'sound', '声音'] },
      { id: 'Tv', name_zh: '电视', keywords: ['tv', 'television', 'screen', '电视'] },
    ]
  },
  {
    name: '媒体与设计',
    groupIcon: 'Palette',
    icons: [
      { id: 'Image', name_zh: '图片', keywords: ['image', 'picture', 'photo', '图像', '照片'] },
      { id: 'Images', name_zh: '图库', keywords: ['images', 'gallery', '图集'] },
      { id: 'Music', name_zh: '音乐', keywords: ['music', 'note', 'audio', '音符', '音频'] },
      { id: 'Play', name_zh: '播放', keywords: ['play', 'start', '开始'] },
      { id: 'Pause', name_zh: '暂停', keywords: ['pause', 'stop', '停止'] },
      { id: 'StopCircle', name_zh: '停止', keywords: ['stop', 'end', '结束'] },
      { id: 'FastForward', name_zh: '快进', keywords: ['fast forward', 'next', '快进'] },
      { id: 'Rewind', name_zh: '快退', keywords: ['rewind', 'prev', '快退'] },
      { id: 'Volume2', name_zh: '音量开', keywords: ['volume', 'loud', '声音'] },
      { id: 'VolumeX', name_zh: '静音', keywords: ['mute', 'quiet', '静音'] },
      { id: 'Wand2', name_zh: '魔法棒', keywords: ['magic', 'wand', 'design', '魔法', '设计'] },
      { id: 'Palette', name_zh: '调色板', keywords: ['palette', 'color', 'art', '颜色', '艺术'] },
      { id: 'Brush', name_zh: '画笔', keywords: ['brush', 'paint', '刷子'] },
      { id: 'Type', name_zh: '文字', keywords: ['type', 'text', 'font', '文本', '字体'] },
      { id: 'Layout', name_zh: '布局', keywords: ['layout', 'grid', '网格', '排版'] },
      { id: 'Scissors', name_zh: '剪刀', keywords: ['scissors', 'cut', '剪切'] },
      { id: 'Crop', name_zh: '裁剪', keywords: ['crop', 'image', '切图'] },
      { id: 'AlignCenter', name_zh: '居中对齐', keywords: ['align', 'center', 'text', '居中'] },
      { id: 'AlignJustify', name_zh: '两端对齐', keywords: ['align', 'justify', 'text', '对齐'] },
      { id: 'AlignLeft', name_zh: '左对齐', keywords: ['align', 'left', 'text', '左对齐'] },
      { id: 'AlignRight', name_zh: '右对齐', keywords: ['align', 'right', 'text', '右对齐'] },
      { id: 'Bold', name_zh: '加粗', keywords: ['bold', 'text', '加粗'] },
      { id: 'Italic', name_zh: '斜体', keywords: ['italic', 'text', '斜体'] },
      { id: 'Underline', name_zh: '下划线', keywords: ['underline', 'text', '下划线'] },
      { id: 'PenTool', name_zh: '钢笔工具', keywords: ['pen', 'vector', 'draw', '钢笔', '矢量'] },
      { id: 'Focus', name_zh: '对焦', keywords: ['focus', 'camera', '对焦', '聚焦'] },
      { id: 'Maximize', name_zh: '最大化', keywords: ['maximize', 'fullscreen', '最大化'] },
      { id: 'Minimize', name_zh: '最小化', keywords: ['minimize', 'shrink', '最小化'] },
      { id: 'VideoOff', name_zh: '关闭视频', keywords: ['video', 'off', 'camera', '关闭'] },
    ]
  },
  {
    name: '文件与开发',
    groupIcon: 'Folder',
    icons: [
      { id: 'File', name_zh: '文件', keywords: ['file', 'document', '文档'] },
      { id: 'FileText', name_zh: '文本文件', keywords: ['text', 'document', 'page', '页面', '文章'] },
      { id: 'FileCode', name_zh: '代码文件', keywords: ['code', 'script', '脚本'] },
      { id: 'FileJson', name_zh: 'JSON文件', keywords: ['json', 'data', '数据'] },
      { id: 'Folder', name_zh: '文件夹', keywords: ['folder', 'directory', '目录'] },
      { id: 'FolderOpen', name_zh: '打开的文件夹', keywords: ['open', 'folder', '目录'] },
      { id: 'FolderPlus', name_zh: '新建文件夹', keywords: ['new', 'folder', '新建'] },
      { id: 'Archive', name_zh: '归档', keywords: ['archive', 'zip', '压缩', '收藏'] },
      { id: 'Box', name_zh: '盒子', keywords: ['box', 'package', '包', '组件'] },
      { id: 'Code', name_zh: '代码', keywords: ['code', 'programming', '开发', '源码'] },
      { id: 'Terminal', name_zh: '终端', keywords: ['terminal', 'console', 'cli', '命令行', '控制台'] },
      { id: 'Database', name_zh: '数据库', keywords: ['database', 'storage', 'data', '存储', '数据'] },
      { id: 'HardDrive', name_zh: '硬盘', keywords: ['disk', 'storage', '存储'] },
      { id: 'Server', name_zh: '服务器', keywords: ['server', 'host', '主机', '服务'] },
      { id: 'Cloud', name_zh: '云', keywords: ['cloud', 'internet', '云端'] },
      { id: 'Cpu', name_zh: '芯片', keywords: ['cpu', 'processor', '处理器', '算力'] },
      { id: 'GitBranch', name_zh: '分支', keywords: ['git', 'branch', '分支'] },
      { id: 'GitMerge', name_zh: '合并', keywords: ['git', 'merge', '合并'] },
      { id: 'AppWindow', name_zh: '应用窗口', keywords: ['app', 'window', 'ui', '窗口', '应用'] },
      { id: 'Binary', name_zh: '二进制', keywords: ['binary', 'code', 'data', '代码', '数据'] },
      { id: 'Bug', name_zh: 'Bug', keywords: ['bug', 'issue', 'insect', '漏洞', '虫子'] },
      { id: 'Code2', name_zh: '代码(样式2)', keywords: ['code', 'developer', '代码'] },
      { id: 'Command', name_zh: '命令', keywords: ['command', 'keyboard', 'mac', '命令'] },
      { id: 'Container', name_zh: '容器', keywords: ['container', 'docker', 'box', '容器'] },
      { id: 'Network', name_zh: '网络', keywords: ['network', 'connections', '网络'] },
      { id: 'Webhook', name_zh: 'Webhook', keywords: ['webhook', 'api', 'hook', '接口'] },
      { id: 'Workflow', name_zh: '工作流', keywords: ['workflow', 'process', '流程'] },
      { id: 'Braces', name_zh: '大括号', keywords: ['braces', 'code', 'json', '括号'] },
      { id: 'Brackets', name_zh: '中括号', keywords: ['brackets', 'code', 'array', '括号'] },
    ]
  },
  {
    name: '科学与教育',
    groupIcon: 'BookOpen',
    icons: [
      { id: 'Book', name_zh: '书', keywords: ['book', 'read', '书籍', '阅读'] },
      { id: 'BookOpen', name_zh: '打开的书', keywords: ['book', 'read', '学习', '阅读'] },
      { id: 'GraduationCap', name_zh: '毕业帽', keywords: ['graduation', 'school', 'education', '教育', '学校'] },
      { id: 'Lightbulb', name_zh: '灯泡', keywords: ['idea', 'lightbulb', 'inspiration', '灵感', '想法'] },
      { id: 'Library', name_zh: '图书馆', keywords: ['library', 'books', 'building', '藏书'] },
      { id: 'FlaskConical', name_zh: '烧瓶', keywords: ['flask', 'science', 'chemistry', '科学', '实验'] },
      { id: 'Microscope', name_zh: '显微镜', keywords: ['microscope', 'science', 'research', '研究'] },
      { id: 'Telescope', name_zh: '望远镜', keywords: ['telescope', 'space', 'astronomy', '太空'] },
      { id: 'Globe', name_zh: '地球仪', keywords: ['globe', 'world', 'earth', '世界', '地球'] },
      { id: 'Compass', name_zh: '指南针', keywords: ['compass', 'navigation', 'direction', '方向', '导航'] },
      { id: 'Atom', name_zh: '原子', keywords: ['atom', 'science', 'physics', '物理'] },
      { id: 'Dna', name_zh: 'DNA', keywords: ['dna', 'biology', 'science', '生物'] },
      { id: 'Brain', name_zh: '大脑', keywords: ['brain', 'mind', 'ai', '智能', '思考'] },
      { id: 'TestTube', name_zh: '试管', keywords: ['test tube', 'science', 'chemistry', '实验'] },
      { id: 'TestTubes', name_zh: '多支试管', keywords: ['test tubes', 'science', 'chemistry', '实验'] },
      { id: 'Stethoscope', name_zh: '听诊器', keywords: ['stethoscope', 'medical', 'doctor', '医疗', '医生'] },
      { id: 'Biohazard', name_zh: '生化危机', keywords: ['biohazard', 'danger', 'warning', '危险'] },
      { id: 'Radiation', name_zh: '辐射', keywords: ['radiation', 'danger', 'warning', '核', '辐射'] },
      { id: 'Leaf', name_zh: '树叶', keywords: ['leaf', 'nature', 'plant', '自然', '植物'] },
    ]
  },
  {
    name: '生活与购物',
    groupIcon: 'ShoppingCart',
    icons: [
      { id: 'ShoppingCart', name_zh: '购物车', keywords: ['cart', 'shopping', 'buy', '购买', '购物'] },
      { id: 'ShoppingBag', name_zh: '购物袋', keywords: ['bag', 'shopping', 'buy', '购物袋'] },
      { id: 'Gift', name_zh: '礼物', keywords: ['gift', 'present', '礼品', '赠送'] },
      { id: 'Coffee', name_zh: '咖啡', keywords: ['coffee', 'cup', 'drink', '饮料', '杯子'] },
      { id: 'Utensils', name_zh: '餐具', keywords: ['food', 'eat', 'restaurant', '餐饮', '刀叉'] },
      { id: 'Plane', name_zh: '飞机', keywords: ['plane', 'travel', 'flight', '旅行', '航班'] },
      { id: 'Car', name_zh: '汽车', keywords: ['car', 'vehicle', 'drive', '车', '交通'] },
      { id: 'Ticket', name_zh: '票', keywords: ['ticket', 'pass', 'event', '门票'] },
      { id: 'Umbrella', name_zh: '雨伞', keywords: ['umbrella', 'rain', 'weather', '雨天'] },
      { id: 'Sun', name_zh: '太阳', keywords: ['sun', 'day', 'weather', '晴天', '白天'] },
      { id: 'Moon', name_zh: '月亮', keywords: ['moon', 'night', 'weather', '晚上', '黑夜'] },
      { id: 'Cloud', name_zh: '云朵', keywords: ['cloud', 'weather', '天气'] },
      { id: 'Apple', name_zh: '苹果', keywords: ['apple', 'food', 'fruit', '水果'] },
      { id: 'Cake', name_zh: '蛋糕', keywords: ['cake', 'dessert', 'birthday', '甜点', '生日'] },
      { id: 'Carrot', name_zh: '胡萝卜', keywords: ['carrot', 'vegetable', 'food', '蔬菜'] },
      { id: 'Pizza', name_zh: '披萨', keywords: ['pizza', 'food', 'fast food', '食物'] },
      { id: 'Wine', name_zh: '红酒', keywords: ['wine', 'glass', 'drink', '酒'] },
      { id: 'Beer', name_zh: '啤酒', keywords: ['beer', 'drink', 'bar', '酒'] },
      { id: 'Tent', name_zh: '帐篷', keywords: ['tent', 'camping', 'outdoors', '露营'] },
      { id: 'Trees', name_zh: '树林', keywords: ['trees', 'forest', 'nature', '自然', '森林'] },
      { id: 'Flame', name_zh: '火焰', keywords: ['flame', 'fire', 'hot', '火', '热门'] },
      { id: 'Snowflake', name_zh: '雪花', keywords: ['snowflake', 'winter', 'cold', '雪', '冷'] },
      { id: 'Wind', name_zh: '风', keywords: ['wind', 'weather', 'air', '天气', '风'] },
    ]
  },
  {
    name: '方向与控制',
    groupIcon: 'Compass',
    icons: [
      { id: 'ArrowRight', name_zh: '向右箭头', keywords: ['arrow', 'right', 'next', '右', '下一步'] },
      { id: 'ArrowLeft', name_zh: '向左箭头', keywords: ['arrow', 'left', 'prev', '左', '上一步'] },
      { id: 'ArrowUp', name_zh: '向上箭头', keywords: ['arrow', 'up', 'top', '上', '顶部'] },
      { id: 'ArrowDown', name_zh: '向下箭头', keywords: ['arrow', 'down', 'bottom', '下', '底部'] },
      { id: 'ChevronRight', name_zh: '右折线', keywords: ['chevron', 'right', 'next', '右'] },
      { id: 'ChevronLeft', name_zh: '左折线', keywords: ['chevron', 'left', 'prev', '左'] },
      { id: 'ChevronDown', name_zh: '下折线', keywords: ['chevron', 'down', 'expand', '展开', '下'] },
      { id: 'ChevronUp', name_zh: '上折线', keywords: ['chevron', 'up', 'collapse', '折叠', '上'] },
      { id: 'ChevronsRight', name_zh: '双向右', keywords: ['chevrons', 'right', 'fast forward'] },
      { id: 'ChevronsLeft', name_zh: '双向左', keywords: ['chevrons', 'left', 'rewind'] },
      { id: 'Maximize2', name_zh: '全屏', keywords: ['maximize', 'fullscreen', 'expand', '放大'] },
      { id: 'Minimize2', name_zh: '退出全屏', keywords: ['minimize', 'shrink', '缩小'] },
      { id: 'Move', name_zh: '移动', keywords: ['move', 'pan', '拖动'] },
      { id: 'Menu', name_zh: '菜单', keywords: ['menu', 'hamburger', '汉堡菜单'] },
      { id: 'Filter', name_zh: '漏斗/筛选', keywords: ['filter', 'sort', '过滤'] },
      { id: 'SlidersHorizontal', name_zh: '滑块调节', keywords: ['sliders', 'settings', 'adjust', '调节'] },
      { id: 'ArrowDownLeft', name_zh: '左下箭头', keywords: ['arrow', 'down', 'left', '左下'] },
      { id: 'ArrowDownRight', name_zh: '右下箭头', keywords: ['arrow', 'down', 'right', '右下'] },
      { id: 'ArrowUpLeft', name_zh: '左上箭头', keywords: ['arrow', 'up', 'left', '左上'] },
      { id: 'ArrowUpRight', name_zh: '右上箭头', keywords: ['arrow', 'up', 'right', '右上'] },
      { id: 'List', name_zh: '列表', keywords: ['list', 'items', 'menu', '清单'] },
      { id: 'ListFilter', name_zh: '列表过滤', keywords: ['list', 'filter', 'sort', '筛选'] },
      { id: 'ListOrdered', name_zh: '有序列表', keywords: ['list', 'ordered', 'numbers', '排序'] },
      { id: 'Hash', name_zh: '井号', keywords: ['hash', 'tag', 'number', '标签'] },
    ]
  }
];

export const PRESET_COLORS = [
  '#2196F3', // 蓝
  '#EF5350', // 红
  '#FF9800', // 橙
  '#FBC02D', // 黄
  '#4CAF50', // 绿
  '#9C27B0', // 紫
  '#E91E63', // 粉
  '#795548', // 棕
  '#607D8B', // 蓝灰
  '#9E9E9E', // 灰
];
